import Link from "next/link";
import { AppHeader } from "@/components/app-header";
import { DashboardClient } from "@/components/dashboard-client";
import { requireUser } from "@/lib/auth";
import { listAssets } from "@/lib/assets";
import { listPendingInvitesForEmail, listUserWorkspaces } from "@/lib/workspaces";

export const dynamic="force-dynamic";
export default async function DashboardPage(){const user=await requireUser();const[assets,workspaces,invites]=await Promise.all([listAssets(user.id),listUserWorkspaces(user.id),listPendingInvitesForEmail(user.email)]);const activeCount=assets.filter(a=>!a.archived_at).length;const hasSharedWorkspace=workspaces.some(w=>w.kind!=="PERSONAL");const hasService=assets.some(a=>a.next_service_date);return <main className="app-page"><div className="container"><AppHeader name={user.name}/><section className="dashboard-head"><div><span className="eyebrow">Deine Sammlung</span><h1>Meine Pässe</h1><p>{activeCount} {activeCount===1?"aktiver Objektpass":"aktive Objektpässe"} · {workspaces.length} {workspaces.length===1?"Bereich":"Bereiche"}</p></div><Link className="button" href="/app/assets/new">+ Neues Objekt</Link></section><section className="dashboard-quicklinks"><Link href="/app/service"><span>W</span><div><b>Service-Center</b><small>Wartungen & Fristen</small></div></Link><Link href="/app/notifications" className={invites.length?"attention":""}><span>!</span><div><b>Hinweise{invites.length?` · ${invites.length}`:""}</b><small>Fristen & Einladungen</small></div></Link><Link href="/app/team"><span>+</span><div><b>Bereiche</b><small>Haushalt & Team</small></div></Link><Link href="/app/activity"><span>↻</span><div><b>Aktivität</b><small>Letzte Änderungen</small></div></Link></section>{assets.length===0?<section className="onboarding-panel"><div className="onboarding-copy"><span className="eyebrow">Schnellstart</span><h2>NavoPass in drei Schritten einrichten</h2><p>Du kannst sofort persönlich starten und später Familie oder Team dazunehmen.</p></div><div className="onboarding-steps"><Link href="/app/assets/new" className="done-ready"><span>1</span><div><b>Ersten Pass anlegen</b><small>Gerät, Fahrzeug, Werkzeug oder Immobilie</small></div><strong>→</strong></Link><Link href="/app/service" className={hasService?"done":""}><span>2</span><div><b>Wartung hinterlegen</b><small>NavoPass erinnert dich an Fristen</small></div><strong>{hasService?"✓":"→"}</strong></Link><Link href="/app/team" className={hasSharedWorkspace?"done":""}><span>3</span><div><b>Optional gemeinsam nutzen</b><small>Haushalt oder Team mit Rollen</small></div><strong>{hasSharedWorkspace?"✓":"→"}</strong></Link></div></section>:<DashboardClient assets={assets} workspaceCount={workspaces.length}/>}</div></main>;}
