import Link from "next/link";
import { assignServiceJobAction, cancelServiceJobAction, createServiceJobAction, reopenServiceJobAction, startServiceJobAction } from "@/app/actions/service-jobs";
import { AppHeader } from "@/components/app-header";
import { requireUser } from "@/lib/auth";
import { listAssets, roleCanManage } from "@/lib/assets";
import { ensureCustomerSchema } from "@/lib/customer-schema";
import { query } from "@/lib/db";

export const dynamic = "force-dynamic";
type Job={id:string;owner_user_id:string;assigned_user_id:string|null;assigned_name:string|null;title:string;scheduled_for:string|null;notes:string|null;priority:"LOW"|"NORMAL"|"HIGH";status:"OPEN"|"IN_PROGRESS"|"DONE"|"CANCELLED";completed_event_id:string|null;created_at:string;asset_id:string;asset_name:string;public_id:string;customer_id:string|null;customer_name:string|null;customer_email:string|null;customer_city:string|null};
type Customer={id:string;name:string;city:string|null}; type Assignment={id:string;service_customer_id:string|null}; type Technician={id:string;name:string;email:string};
function when(value:string|null){return value?new Intl.DateTimeFormat("de-DE",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"Ohne Termin";}
function statusLabel(value:Job["status"]){if(value==="DONE")return"Erledigt";if(value==="CANCELLED")return"Storniert";if(value==="IN_PROGRESS")return"In Arbeit";return"Offen";}
function priorityLabel(value:Job["priority"]){return value==="HIGH"?"Dringend":value==="LOW"?"Niedrig":"Normal";}

export default async function ServiceJobsPage({searchParams}:{searchParams:Promise<{success?:string;error?:string;status?:string;mine?:string}>}){
  const user=await requireUser(); const {success,error,status,mine}=await searchParams;
  if(user.account_type!=="PROFESSIONAL") return <main className="app-page"><div className="container"><AppHeader name={user.name}/><section className="empty-state compact"><div className="empty-icon">A</div><h1>Serviceaufträge</h1><p>Der Auftragsbereich ist für Firmen- und Technikerprofile vorgesehen.</p><Link className="button" href="/app/profil">Profil auf beruflich umstellen</Link></section></div></main>;
  await ensureCustomerSchema();
  const assets=(await listAssets(user.id)).filter(a=>!a.archived_at&&roleCanManage(a,user.id));
  const assetIds=assets.map(a=>a.id);
  const assignments=assetIds.length?(await query<Assignment>("SELECT id,service_customer_id FROM assets WHERE id=ANY($1::uuid[])",[assetIds])).rows:[];
  const customerIds=[...new Set(assignments.map(a=>a.service_customer_id).filter((v):v is string=>Boolean(v)))];
  const customers=customerIds.length?(await query<Customer>("SELECT id,name,city FROM service_customers WHERE user_id=$1 AND id=ANY($2::uuid[]) ORDER BY name",[user.id,customerIds])).rows:[];
  const technicians=assetIds.length?(await query<Technician>(`
    SELECT DISTINCT u.id,u.name,u.email
      FROM assets a
      JOIN workspace_members wm ON wm.workspace_id=a.workspace_id AND wm.role IN ('OWNER','ADMIN','EDITOR')
      JOIN users u ON u.id=wm.user_id
     WHERE a.id=ANY($1::uuid[])
     ORDER BY u.name,u.email`,[assetIds])).rows:[];
  if(!technicians.some(t=>t.id===user.id)) technicians.unshift({id:user.id,name:user.name,email:user.email});
  const jobs=(await query<Job>(`
    SELECT j.id,j.user_id AS owner_user_id,j.assigned_user_id,au.name AS assigned_name,j.title,j.scheduled_for,j.notes,j.priority,j.status,j.completed_event_id,j.created_at,
           a.id AS asset_id,a.name AS asset_name,a.public_id,c.id AS customer_id,c.name AS customer_name,c.email AS customer_email,c.city AS customer_city
      FROM service_jobs j
      JOIN assets a ON a.id=j.asset_id
      LEFT JOIN users au ON au.id=j.assigned_user_id
      LEFT JOIN service_customers c ON c.id=j.customer_id
     WHERE j.user_id=$1 OR j.assigned_user_id=$1
     ORDER BY CASE j.status WHEN 'IN_PROGRESS' THEN 0 WHEN 'OPEN' THEN 1 WHEN 'DONE' THEN 2 ELSE 3 END,j.scheduled_for NULLS LAST,j.created_at DESC`,[user.id])).rows;
  const now=Date.now(); const endToday=new Date(); endToday.setHours(23,59,59,999);
  const open=jobs.filter(j=>j.status==="OPEN").length; const active=jobs.filter(j=>j.status==="IN_PROGRESS").length;
  const overdue=jobs.filter(j=>(j.status==="OPEN"||j.status==="IN_PROGRESS")&&j.scheduled_for&&new Date(j.scheduled_for).getTime()<now).length;
  const today=jobs.filter(j=>(j.status==="OPEN"||j.status==="IN_PROGRESS")&&j.scheduled_for&&new Date(j.scheduled_for).getTime()>=new Date(new Date().setHours(0,0,0,0)).getTime()&&new Date(j.scheduled_for).getTime()<=endToday.getTime()).length;
  const allowed=new Set(["OPEN","IN_PROGRESS","DONE","CANCELLED"]); const selected=allowed.has(status||"")?status:null; const onlyMine=mine==="1";
  let visible=selected?jobs.filter(j=>j.status===selected):jobs; if(onlyMine) visible=visible.filter(j=>j.assigned_user_id===user.id);

  return <main className="app-page"><div className="container"><AppHeader name={user.name}/><section className="service-head"><div><span className="eyebrow">Kundendienst</span><h1>Serviceaufträge</h1><p>Disposition, Technikerzuweisung, Durchführung und fertiger Kundenbericht in einem Ablauf.</p></div><Link className="button ghost" href="/app/kunden">Kunden & Standorte</Link></section>{success&&<p className="form-success" role="status">{success}</p>}{error&&<p className="form-error" role="alert">{error}</p>}
    <section className="pass-status-grid"><article className="status-card"><span>Offen</span><b>{open}</b><small>noch nicht gestartet</small></article><article className={`status-card ${active?"warning":"ok"}`}><span>In Arbeit</span><b>{active}</b><small>laufende Einsätze</small></article><article className={`status-card ${today?"warning":"ok"}`}><span>Heute</span><b>{today}</b><small>terminierte Einsätze</small></article><article className={`status-card ${overdue?"danger":"ok"}`}><span>Überfällig</span><b>{overdue}</b><small>Termin überschritten</small></article></section>
    <section className="detail-grid"><article className="panel"><div className="panel-head"><div><span className="eyebrow">Planung</span><h2>Serviceauftrag anlegen</h2></div></div>{assets.length===0?<p className="muted">Keine Anlagen vorhanden, die du disponieren darfst. Dir zugewiesene Einsätze erscheinen trotzdem unten.</p>:<form action={createServiceJobAction} className="compact-form"><label>Anlage<select name="assetId" required>{assets.map(a=><option value={a.id} key={a.id}>{a.name} · {a.category}</option>)}</select></label><label>Kunde / Standort<select name="customerId" defaultValue=""><option value="">Ohne Kundenzuordnung</option>{customers.map(c=><option value={c.id} key={c.id}>{c.name}{c.city?` · ${c.city}`:""}</option>)}</select></label><div className="two-cols"><label>Auftrag<input name="title" defaultValue="Wartung / Service" maxLength={180} required/></label><label>Priorität<select name="priority" defaultValue="NORMAL"><option value="LOW">Niedrig</option><option value="NORMAL">Normal</option><option value="HIGH">Dringend</option></select></label></div><div className="two-cols"><label>Termin<input name="scheduledFor" type="datetime-local"/></label><label>Techniker<select name="assignedUserId" defaultValue={user.id}>{technicians.map(t=><option value={t.id} key={t.id}>{t.id===user.id?"Ich":t.name} · {t.email}</option>)}</select></label></div><small className="muted">Zuweisbar sind Teammitglieder mit Bearbeitungsrecht. NavoPass prüft zusätzlich den Zugriff auf die ausgewählte Anlage.</small><label>Auftragsnotiz<textarea name="notes" rows={3} maxLength={2000}/></label><button className="button" type="submit">Serviceauftrag anlegen</button></form>}</article><article className="panel"><div className="panel-head"><div><span className="eyebrow">Disposition</span><h2>Ansicht filtern</h2></div></div><div className="form-actions" style={{flexWrap:"wrap"}}><Link className={`button ${!selected&&!onlyMine?"":"ghost"} small`} href="/app/auftraege">Alle</Link><Link className={`button ${onlyMine?"":"ghost"} small`} href="/app/auftraege?mine=1">Meine Einsätze</Link><Link className={`button ${selected==="OPEN"?"":"ghost"} small`} href="/app/auftraege?status=OPEN">Offen</Link><Link className={`button ${selected==="IN_PROGRESS"?"":"ghost"} small`} href="/app/auftraege?status=IN_PROGRESS">In Arbeit</Link><Link className={`button ${selected==="DONE"?"":"ghost"} small`} href="/app/auftraege?status=DONE">Erledigt</Link></div><p className="muted" style={{marginTop:18}}>Disponenten können Teammitglieder zuweisen. Zugewiesene Techniker sehen den Einsatz in ihrer eigenen Auftragsansicht und können ihn starten sowie dokumentieren.</p></article></section>
    <section className="panel"><div className="panel-head"><div><span className="eyebrow">Auftragsliste</span><h2>{onlyMine?"Meine Einsätze":selected?statusLabel(selected as Job["status"]):"Alle Serviceaufträge"}</h2></div><span className="count-pill">{visible.length}</span></div>{visible.length===0?<p className="muted">Keine Serviceaufträge in dieser Ansicht.</p>:<div className="service-list">{visible.map(job=>{const late=(job.status==="OPEN"||job.status==="IN_PROGRESS")&&job.scheduled_for&&new Date(job.scheduled_for).getTime()<now;const owner=job.owner_user_id===user.id;return <article className={`service-card ${late?"danger":job.status==="IN_PROGRESS"?"warning":"neutral"}`} key={job.id}><div className="service-date"><span>{statusLabel(job.status)} · {priorityLabel(job.priority)}</span><b>{when(job.scheduled_for)}</b><small>{job.customer_name||"Ohne Kunde"}</small></div><div className="service-main"><span className="asset-category">{job.customer_city||"Kundendienst"}</span><h2>{job.title}</h2><p>{job.asset_name}{job.notes?` · ${job.notes}`:""}</p><span className="interval-chip">Techniker: {job.assigned_name||"nicht zugewiesen"}</span>{late&&<span className="interval-chip">Termin überschritten</span>}</div><div className="service-actions">{owner&&(job.status==="OPEN"||job.status==="IN_PROGRESS")&&technicians.length>0&&<form action={assignServiceJobAction} style={{display:"flex",gap:6,alignItems:"center"}}><input type="hidden" name="jobId" value={job.id}/><select name="assignedUserId" defaultValue={job.assigned_user_id||user.id}>{technicians.map(t=><option value={t.id} key={t.id}>{t.id===user.id?"Ich":t.name}</option>)}</select><button className="button ghost small" type="submit">Zuweisen</button></form>}{job.status==="OPEN"&&<><form action={startServiceJobAction}><input type="hidden" name="jobId" value={job.id}/><button className="button small" type="submit">Einsatz starten</button></form><Link className="button ghost small" href={`/app/assets/${job.asset_id}/service?job=${job.id}`}>Direkt dokumentieren</Link></>}{job.status==="IN_PROGRESS"&&<><Link className="button small" href={`/app/assets/${job.asset_id}/service?job=${job.id}`}>Servicebericht erfassen</Link><form action={reopenServiceJobAction}><input type="hidden" name="jobId" value={job.id}/><button className="button ghost small" type="submit">Zurück auf offen</button></form></>}{owner&&(job.status==="OPEN"||job.status==="IN_PROGRESS")&&<form action={cancelServiceJobAction}><input type="hidden" name="jobId" value={job.id}/><button className="button ghost small" type="submit">Stornieren</button></form>}{job.status==="DONE"&&job.completed_event_id&&<Link className="button small" href={`/app/assets/${job.asset_id}/service/${job.completed_event_id}/bericht`}>Bericht öffnen</Link>}<Link className="button ghost small" href={`/app/assets/${job.asset_id}`}>Objektpass</Link></div></article>})}</div>}</section>
  </div></main>;
}
