"use client";

import { useLayoutEffect, useRef, useState, type ReactNode } from "react";

const translations: Array<[string, string]> = [
  ["“ inklusive Historie und Uploads dauerhaft löschen?", "” including history and uploads permanently?"],
  ["“ wirklich löschen? Die Pässe werden in deinen persönlichen Bereich verschoben.", "” permanently? The passes will be moved to your personal workspace."],
  ["“ wirklich löschen?", "” permanently?"],
  ["aus diesem Bereich entfernen?", "from this workspace?"],
  ["Bereich „", "Workspace “"],
  ["Einladung zu „", "Invitation to “"],
  ["Das Abo ist zur Kündigung vorgemerkt", "The subscription is scheduled for cancellation"],
  ["und läuft bis", "and runs until"],
  ["Du brauchst einen eigenen oder von dir administrierten Objektpass.", "You need an asset pass that you own or administer."],
  ["Du kannst den Link manuell weitergeben.", "You can share the link manually."],
  ["E-Mail-Versand ist fehlgeschlagen. Du kannst den Link manuell weitergeben.", "Email delivery failed. You can share the link manually."],
  ["Du nutzt bereits", "You already use"],
  ["Innerhalb der nächsten", "Within the next"],
  ["Tage steht aktuell keine hinterlegte Wartung oder Garantiefrist an.", "days, no recorded maintenance or warranty deadline is currently due."],
  ["Wartungen, Garantiefristen und offene Einladungen an einem Ort. Dein aktueller Vorlauf beträgt", "Maintenance, warranty deadlines, and pending invitations in one place. Your current reminder window is"],
  ["Zugriff vorgesehen bis", "Access planned until"],
  ["QR-Code für", "QR code for"],
  ["Einsätze:", "Jobs:"],
  ["Datei / Link", "File / link"],
  ["/ Monat", "/ month"],
  ["/ Jahr", "/ year"],
  ["1 Tag", "1 day"],
  ["1 Jahr", "1 year"],
  ["· bestätigt", "· confirmed"],
  ["geöffnet", "opened"],
  ["Du", "You"],
  ["Zugriff", "Access"],
  ["· gültig bis", "· valid until"],
  ["← Meine Pässe", "← My passes"],
  ["← Serviceaufträge", "← Service jobs"],
  ["← Zurück zu", "← Back to"],
  ["← Zurück zu den Tarifen", "← Back to plans"],
  ["+ Ereignis hinzufügen", "+ Add event"],
  ["1 pro Objekt", "1 per asset"],
  ["2 pro Objekt", "2 per asset"],
  ["1 Stück", "1 item"],
  ["2 Stück", "2 items"],
  ["aktive Objektpässe", "active asset passes"],
  ["Bearbeiter – Pässe bearbeiten", "Editor – edit passes"],
  ["Benachrichtigungen öffnen →", "Open notifications →"],
  ["Bereich erstellen", "Create workspace"],
  ["Bereich filtern", "Filter workspace"],
  ["Bereich verlassen", "Leave workspace"],
  ["Bereich verwalten", "Manage workspace"],
  ["Datum:", "Date:"],
  ["Du verlierst den Zugriff auf alle gemeinsamen Pässe dieses Bereichs.", "You will lose access to all shared passes in this workspace."],
  ["Erste Wartung", "First maintenance"],
  ["Garantie oder Wartung", "Warranty or maintenance"],
  ["Handlungsbedarf · Überfällig", "Action required · Overdue"],
  ["In diesem Bereich hast du die Rolle Betrachter und kannst den Pass nicht bearbeiten.", "You have the Viewer role in this workspace and cannot edit the pass."],
  ["Mehr als Business benötigt? Kontakt aufnehmen →", "Need more than Business? Contact us →"],
  ["Neuer Bereich", "New workspace"],
  ["Noch keine Zahlung:", "No payment yet:"],
  ["Objekte, Kunden und Fristen suchen…", "Search assets, customers, and deadlines…"],
  ["Öffnen →", "Open →"],
  ["Ohne Wartung", "No maintenance"],
  ["Pässe durchsuchen…", "Search passes…"],
  ["Persönlich & gemeinsam", "Personal & shared"],
  ["Pro Gerät sinnvoll:", "Recommended per asset:"],
  ["Profil auf beruflich umstellen", "Switch profile to professional"],
  ["QR-Code & Aufkleber öffnen →", "Open QR code & stickers →"],
  ["Stück ·", "items ·"],
  ["Team / Firma", "Team / company"],
  ["Wartung / Service", "Maintenance / service"],
  ["Wartung / Service dokumentieren", "Document maintenance / service"],
  ["Wartung & Garantie", "Maintenance & warranty"],
  ["Weiter zur sicheren Zahlung bei Stripe →", "Continue to secure payment with Stripe →"],
  ["z. B. Hersteller-Anleitung", "e.g. manufacturer manual"],
  ["z. B. Wartung durchgeführt", "e.g. maintenance completed"],
  ["Für private Nutzer mit vielen Geräten, Fahrzeugen und Dokumenten.", "For private users with many devices, vehicles, and documents."],
  ["Für Familien und Haushalte, die Dinge gemeinsam verwalten.", "For families and households managing things together."],
  ["Heizung & Klima", "Heating & climate"],
  ["Haushalt", "Household"],
  ["Fahrzeug", "Vehicle"],
  ["Fahrrad", "Bicycle"],
  ["Werkzeug", "Tools"],
  ["Elektronik", "Electronics"],
  ["Maschine", "Machine"],
  ["Immobilie", "Property"],
  ["Sonstiges", "Other"],
  ["Business-Einsatz", "Business job"],
  ["nicht zugewiesen", "unassigned"],
  ["Ich", "Me"],
  [", die 14-tägige Widerrufsfrist und die elektronische Widerrufsmöglichkeit zur Kenntnis genommen.", ", the 14-day withdrawal period, and the electronic withdrawal option."],
  [". Die Kündigung eines laufenden Abos ist zusätzlich über", ". An active subscription can also be cancelled via"],
  ["Verträge hier kündigen", "Cancel contract here"],
  ["Bitte LÖSCHEN oder DELETE eingeben", "Please enter DELETE"],
  ["Ich verlange ausdrücklich, dass Kamilunavo mit der kostenpflichtigen NavoPass-Dienstleistung unmittelbar nach erfolgreicher Bestellung und damit vor Ablauf der Widerrufsfrist beginnt. Mir ist bekannt, dass bei einem späteren Widerruf für bereits auf meinen ausdrücklichen Wunsch erbrachte Leistungen unter den gesetzlichen Voraussetzungen Wertersatz geschuldet sein kann.", "I expressly request that Kamilunavo begin providing the paid NavoPass service immediately after successful ordering and before the withdrawal period expires. I understand that, if I later withdraw, statutory compensation may be owed for services already provided at my express request."],
  ["Die Zahlung wird im nächsten Schritt über Stripe abgewickelt. Stripe fragt die Rechnungsadresse ab, damit die Abo-Rechnung vollständig erstellt werden kann. Die angezeigte Gesamtsumme muss dieser Tarifauswahl entsprechen; NavoPass prüft die konfigurierte Stripe-Price-ID zusätzlich serverseitig.", "Payment is processed by Stripe in the next step. Stripe requests the billing address so the subscription invoice can be completed. The displayed total must match this plan selection; NavoPass also verifies the configured Stripe Price ID on the server."],
  ["Nach jedem Abrechnungszeitraum verlängert sich das Abo um einen weiteren gleich langen Abrechnungszeitraum, bis es gekündigt wird. Die ordentliche Kündigung ist zum Ende des laufenden Abrechnungszeitraums möglich.", "After each billing period, the subscription renews for another period of equal length until cancelled. Ordinary cancellation is possible at the end of the current billing period."],
  ["Für kostenpflichtige Fernabsatzverträge besteht für Verbraucher grundsätzlich ein 14-tägiges Widerrufsrecht. Die vollständige Widerrufsbelehrung und elektronische Widerrufsfunktion findest du unter", "Consumers generally have a 14-day right of withdrawal for paid distance contracts. The complete withdrawal information and electronic withdrawal form are available under"],
  ["Der zahlungspflichtige Abschluss erfolgt erst im folgenden Stripe-Checkout. Wird Stripe abgebrochen, wird kein kostenpflichtiger Tarif aktiviert.", "The paid order is completed only in the following Stripe Checkout. If Stripe is cancelled, no paid plan is activated."],
  ["Der E-Mail-Versand hat nicht funktioniert. Die Einladung selbst ist gültig – gib den Link bitte direkt weiter.", "The email could not be sent. The invitation itself is valid – please share the link directly."],
  ["Die eingeladene Person hat den Link per E-Mail erhalten. Du kannst ihn bei Bedarf zusätzlich direkt weitergeben.", "The invitee received the link by email. You can also share it directly if needed."],
  ["Der Link ist 7 Tage gültig und funktioniert nur mit der eingeladenen E-Mail-Adresse.", "The link is valid for 7 days and only works with the invited email address."],
  ["Dieser Tarif ist für persönliche Nutzung ausgelegt.", "This plan is intended for personal use."],
  ["Dieser Bereich gehört nur dir.", "This workspace belongs only to you."],
  ["Einladung angenommen. Du hast jetzt Zugriff auf diesen Bereich.", "Invitation accepted. You now have access to this workspace."],
  ["Du kannst sofort persönlich starten und später Familie oder Team dazunehmen.", "Start personally right away and add family or a team later."],
  ["Gruppiere Objektpässe nach Kunde oder Einsatzort und erkenne sofort, wo Wartungen anstehen.", "Group asset passes by customer or location and immediately see where maintenance is due."],
  ["Öffne den Einladungslink, den dir der Bereichsinhaber geschickt hat.", "Open the invitation link sent by the workspace owner."],
  ["Öffne einen NavoPass direkt am Gerät. Mit entsprechender Berechtigung kannst du anschließend Wartung, Reparatur oder Prüfung dokumentieren.", "Open a NavoPass directly at the asset. With the required permission, you can then document maintenance, repair, or inspection work."],
  ["Prüfe Tarif, Laufzeit und Verbraucherinformationen, bevor du zur sicheren Zahlung bei Stripe wechselst.", "Review the plan, term, and consumer information before continuing to secure payment with Stripe."],
  ["Tarif, Nutzung, Profil, Erinnerungen, Sicherheit, Datenexport und dein NavoPass-Konto an einem Ort.", "Plan, usage, profile, reminders, security, data export, and your NavoPass account in one place."],
  ["Teile Objektpässe mit Familie, Kollegen oder Mitarbeitern – mit klaren Rollen und Rechten.", "Share asset passes with family, colleagues, or employees – with clear roles and permissions."],
  ["Verwalte gemeinsame Bereiche, Einladungen und Rollen für Familie, Kollegen oder Mitarbeiter.", "Manage shared workspaces, invitations, and roles for family, colleagues, or employees."],
  ["Alle anderen NavoPass-Sitzungen abmelden?", "Sign out all other NavoPass sessions?"],
  ["aktive NavoPass-Sitzung", "active NavoPass session"],
  ["gespeichert. Du kannst alle anderen Geräte sofort abmelden.", "saved. You can sign out all other devices immediately."],
  ["Aktive Objektpässe", "Active asset passes"],
  ["Alles im grünen Bereich", "Everything is on track"],
  ["Pass archivieren und öffentlichen Zugriff deaktivieren?", "Archive pass and disable public access?"],
  ["Bestätigung vor Stripe", "Confirmation before Stripe"],
  ["Bestellung prüfen", "Review order"],
  ["Kunde / Auftraggeber", "Customer / client"],
  ["Kunde / Ausführung", "Customer / service"],
  ["Kunde / Standort", "Customer / location"],
  ["Kunde löschen", "Delete customer"],
  ["Wartungen öffnen", "Open maintenance"],
  ["Mehr Platz benötigt?", "Need more capacity?"],
  ["Objektpässe & Service", "Asset passes & service"],
  ["Objektpässe mit insgesamt", "Asset passes with a total of"],
  ["Offene Serviceeinladung zurückziehen?", "Withdraw pending service invitation?"],
  ["Per Link oder öffentlich", "By link or public"],
  ["Profil öffnen", "Open profile"],
  ["Service-Center öffnen", "Open service center"],
  ["Gemeinsame Bereiche nicht verfügbar", "Shared workspaces unavailable"],
  ["Weiter zur sicheren Zahlung bei Stripe", "Continue to secure payment with Stripe"],
  ["Bereich löschen", "Delete workspace"],
  ["Datenexport", "data export"],
  ["Objektpässe", "Asset passes"],
  ["Objekt", "Asset"],
  ["überfällig", "overdue"],
  ["möglich", "possible"],
  ["Alle Wartungen und Garantiefristen im Blick – inklusive automatischer Folgetermine und Kalenderexport.", "Keep track of every maintenance and warranty deadline – including automatic follow-up dates and calendar export."],
  ["Alle Pässe in diesem Bereich sind für die Mitglieder entsprechend ihrer Rolle verfügbar.", "All passes in this workspace are available to members according to their role."],
  ["Beim Löschen werden die Pässe nicht gelöscht, sondern zurück in deinen persönlichen Bereich verschoben.", "Deleting does not remove the passes; they are moved back to your personal workspace."],
  ["Das Konto liegt momentan über mindestens einem Tariflimit. NavoPass sperrt deshalb nur neue Pässe, Uploads, Nutzer oder Bereiche, bis wieder Platz frei ist oder ein größerer Tarif aktiv ist.", "The account is currently above at least one plan limit. NavoPass only blocks new passes, uploads, users, or workspaces until capacity is available or a larger plan is active."],
  ["Deine bestehenden Bereiche und Daten bleiben erhalten. Für weiteres Wachstum brauchst du einen größeren Tarif.", "Your existing workspaces and data remain available. Choose a larger plan to keep growing."],
  ["Der QR-Link folgt der Sichtbarkeit dieses Passes. Mitglieder des Bereichs können private Passdaten entsprechend ihrer Rolle sehen.", "The QR link follows this pass’s visibility. Workspace members can view private pass data according to their role."],
  ["Dieser Bereich ist für Firmen- und Technikerprofile vorgesehen.", "This workspace is intended for company and technician profiles."],
  ["Du kannst die Historie ansehen. Zum Hinzufügen oder Löschen ist mindestens die Rolle Bearbeiter erforderlich.", "You can view the history. Adding or deleting requires at least the Editor role."],
  ["In einem Haushalt oder Team können Mitglieder den Pass entsprechend ihrer Rolle ansehen oder bearbeiten.", "In a household or team, members can view or edit the pass according to their role."],
  ["Kunde und Standort werden automatisch aus der Zuordnung des ausgewählten Objektpasses übernommen.", "Customer and location are taken automatically from the selected asset pass assignment."],
  ["Kunden- und Standortverwaltung gehört zum Business-Tarif.", "Customer and location management is included in the Business plan."],
  ["Ordne auf der Kundenübersicht einen Objektpass diesem Kunden oder Standort zu.", "Assign an asset pass to this customer or location from the customer overview."],
  ["Wähle mehrere Objektpässe aus. Jeder ausgewählte Pass behält seinen eigenen QR-Code; es werden also nicht viele Kopien desselben Geräte-Codes erzeugt.", "Select multiple asset passes. Every selected pass keeps its own QR code, rather than creating many copies of the same asset code."],
  ["Sammelanfragen sind für Firmen-, Techniker- und Serviceprofile vorgesehen. Stelle dein Profil zuerst auf berufliche Nutzung um.", "Combined requests are intended for company, technician, and service profiles. First switch your profile to professional use."],
  ["Für Heizungen, Klimageräte, Werkzeuge oder andere technische Anlagen ist die wetterfeste Variante vorgesehen.", "The weather-resistant version is intended for heating systems, air conditioners, tools, and other technical equipment."],
  ["Servicefreigaben können nur Inhaber oder Admins des Objektpasses verwalten.", "Only owners or admins of the asset pass can manage service access."],
  ["Nur Inhaber oder Admins des Objektpasses können physische QR-Aufkleber anfragen.", "Only owners or admins of the asset pass can request physical QR stickers."],
  ["Optional. Die Unterschrift wird ausschließlich diesem Serviceeintrag zugeordnet.", "Optional. The signature is associated only with this service entry."],
  ["Dein NavoPass-Konto und ein eventuell noch laufendes NavoPass-Abo werden dauerhaft beendet. Wirklich fortfahren?", "Your NavoPass account and any active NavoPass subscription will be permanently ended. Do you really want to continue?"],
  ["Checkout abgeschlossen. Dein Tarif wird automatisch aktiviert, sobald Stripe den bestätigten Abo-Status an NavoPass übermittelt hat.", "Checkout completed. Your plan activates automatically as soon as Stripe sends the confirmed subscription status to NavoPass."],
  ["Bitte Zahlungsmittel im Abo-Portal prüfen.", "Please check your payment method in the subscription portal."],
  ["Deine bestehenden Pässe bleiben vollständig erhalten.", "Your existing passes remain fully available."],
  ["Deine vorhandenen Daten bleiben erhalten.", "Your existing data remains available."],
  ["Der Business-Auftragsbereich ist für berufliche Profile und Unternehmen vorgesehen.", "The Business jobs area is intended for professional profiles and companies."],
  ["Der Kunde hat einen geschützten, 30 Tage gültigen Link erhalten.", "The customer received a protected link valid for 30 days."],
  ["Der bisherige Kundenlink ist nicht mehr gültig.", "The previous customer link is no longer valid."],
  ["Die Einladung ist 7 Tage lang annehmbar. Die gewählte Zugriffsdauer beginnt mit Erstellung der Einladung und endet automatisch.", "The invitation can be accepted for 7 days. The selected access period begins when the invitation is created and ends automatically."],
  ["Die Einladung wurde per E-Mail versendet.", "The invitation was sent by email."],
  ["Für die aktuelle Auswahl haben alle aktiven Pässe einen nächsten Wartungstermin.", "All active passes in the current selection have a next maintenance date."],
  ["Für diesen Pass wurden noch keine QR-Aufkleber angefragt.", "No QR stickers have been requested for this pass yet."],
  ["Für diesen Zeitraum und Filter ist aktuell nichts fällig.", "Nothing is currently due for this period and filter."],
  ["Lege zuerst Geräte oder Anlagen an, für die du Aufkleber benötigst.", "First create the devices or assets for which you need stickers."],
  ["Maximal 2 je Gerät: Hauptaufkleber plus Reserve oder zweite Position.", "Maximum 2 per asset: primary sticker plus a spare or second position."],
  ["Deine Rolle", "Your role"],
  ["Deine Auswahl", "Your selection"],
  ["Deine Sammlung", "Your collection"],
  ["Deine Bereiche", "Your workspaces"],
  ["Alle Einsätze", "All jobs"],
  ["Alle Freigaben", "All access grants"],
  ["Alle Kategorien", "All categories"],
  ["Alle Kunden & Standorte", "All customers & locations"],
  ["Alle", "All"],
  ["Aktive Objektpässe", "Active asset passes"],
  ["laufende Einsätze", "active jobs"],
  ["terminierte Einsätze", "scheduled jobs"],
  ["Firmen & größere Bestände", "Companies & larger inventories"],
  ["Für Firmen & Techniker", "For companies & technicians"],
  ["Geschäftliche Anfrage", "Business enquiry"],
  ["Hinweis zum Start", "Getting started"],
  ["Keine Angaben dokumentiert.", "No information documented."],
  ["Keine Bestellberechtigung", "No permission to order"],
  ["Keine Verwaltungsrechte", "No management permission"],
  ["Keine gültige NavoPass-ID oder kein gültiger NavoPass-QR-Link.", "Not a valid NavoPass ID or QR link."],
  ["Keine passenden Fristen.", "No matching deadlines."],
  ["Noch kein bestellbarer Pass", "No eligible pass yet"],
  ["Noch kein Termin", "No date yet"],
  ["Noch keine Adresse hinterlegt", "No address saved yet"],
  ["Noch keine Anlage zugeordnet", "No asset assigned yet"],
  ["Kamera konnte nicht geöffnet werden. Bitte Kameraberechtigung prüfen oder die Pass-ID manuell eingeben.", "The camera could not be opened. Check camera permission or enter the pass ID manually."],
  ["Dieser Browser unterstützt den direkten QR-Scanner nicht. Nutze die Kamera-App deines Smartphones oder gib die Pass-ID unten ein.", "This browser does not support direct QR scanning. Use your phone’s camera app or enter the pass ID below."],
  ["Alternativ kannst du die normale Kamera-App auf iPhone oder Android verwenden. Ein NavoPass-QR-Code öffnet den Objektpass direkt im Browser.", "Alternatively, use the regular camera app on iPhone or Android. A NavoPass QR code opens the asset pass directly in the browser."],
  ["QR-Aufkleber-Anfrage wurde gespeichert. Wir melden uns zur Bestätigung von Preis und Produktion.", "Your QR sticker request has been saved. We will contact you to confirm pricing and production."],
  ["Feld für Kundenunterschrift", "Customer signature field"],
  ["Zur Bestätigung „LÖSCHEN“ eingeben", "Enter “DELETE” to confirm"],
  ["LÖSCHEN", "DELETE"],
  ["NavoPass erinnert dich an Fristen", "NavoPass reminds you about deadlines"],
  ["Was möchtest du dokumentieren?", "What would you like to document?"],
  ["Wird bei neuen Serviceeinträgen als ausführender Betrieb vorgeschlagen.", "Suggested as the performing company for new service entries."],
  ["Gerät, Fahrzeug, Werkzeug oder Immobilie", "Device, vehicle, tool, or property"],
  ["z. B. Baustelle, Objektbezeichnung oder gewünschte Sortierung", "e.g. construction site, asset name, or preferred sorting"],
  ["z. B. Familie Müller oder Büro Köln", "e.g. Miller family or Cologne office"],
  ["z. B. Rechnung Wärmepumpe", "e.g. heat-pump invoice"],
  ["z. B. Maschine Halle 2, Firmenfahrzeug oder Klimagerät", "e.g. machine in hall 2, company vehicle, or air conditioner"],
  ["z. B. Zugang Heizraum über Hausmeister", "e.g. boiler-room access via caretaker"],
  ["z. B. zweite Position am Gerät oder besondere Rückfrage", "e.g. second position on the asset or a special request"],
  ["Service & Fristen", "Service & deadlines"],
  ["Konto & Datenschutz", "Account & privacy"],
  ["Konto & Zugang", "Account & access"],
  ["Mein Konto", "My account"],
  ["Passwort", "Password"],
  ["Firma", "Company"],
  ["Fristen", "Deadlines"],
  ["jährlich", "annually"],
  ["Jährlich", "Annually"],
  ["Heute fällig", "Due today"],
  ["heute fällig", "due today"],
  ["Morgen fällig", "Due tomorrow"],
  ["morgen fällig", "due tomorrow"],
  ["Sofort prüfen", "Check now"],
  ["Filter zurücksetzen", "Reset filters"],
  ["Zurückziehen", "Withdraw"],
  ["Person hinzufügen", "Add person"],
  ["Einladung erstellen & senden", "Create & send invitation"],
  ["Einladung erstellt", "Invitation created"],
  ["Einladung wurde per E-Mail versendet", "Invitation sent by email"],
  ["Einladung bis", "Invitation until"],
  ["Nächste 30 Tage", "Next 30 days"],
  ["Nächste 7 Tage", "Next 7 days"],
  ["Nächste 90 Tage", "Next 90 days"],
  ["Sammelanfrage für mehrere Geräte", "Combined request for multiple assets"],
  ["QR am echten Objekt", "QR on the physical asset"],
  ["QR am Objekt", "QR on asset"],
  ["QR-Aufkleber für", "QR stickers for"],
  ["QR-Code & Aufkleber öffnen", "Open QR code & stickers"],
  ["Produktion über externen Druckpartner", "Production through an external print partner"],
  ["Pro Gerät sinnvoll", "Recommended per asset"],
  ["Business-Tarif ansehen", "View Business plan"],
  ["Tarif für Zusammenarbeit", "Collaboration plan"],
  ["Zahlung noch nicht abgeschlossen", "Payment not completed"],
  ["Zahlung offen", "Payment due"],
  ["Ändere Stammdaten, Termine, Freigabe und Notizen. Historie und Dokumente bleiben erhalten.", "Update master data, dates, sharing, and notes. History and documents remain intact."],
  ["Kunden, Objekte, Teamzuweisung, Wochenplanung, Durchführung und Berichte in einem Ablauf – branchenunabhängig.", "Customers, assets, team assignments, weekly planning, execution, and reports in one workflow – across industries."],
  ["Kundenverwaltung, Standorte, Service-Disposition und Technikerplanung gehören zum Business-Tarif.", "Customer management, locations, service scheduling, and technician planning are included in the Business plan."],
  ["Eigene Einsatzplanung und Kundenverwaltung benötigen Business. Bereits von einem Business-Konto zugewiesene Einsätze kannst du weiterhin bearbeiten.", "Creating schedules and managing customers requires Business. You can still work on jobs assigned by a Business account."],
  ["Einsätze anlegen, Kunden verwalten, Teammitglieder zuweisen und Zeitkonflikte prüfen ist im Business-Tarif enthalten.", "Creating jobs, managing customers, assigning team members, and checking time conflicts are included in the Business plan."],
  ["Zuweisbar sind Teammitglieder mit Bearbeitungsrecht. Termine werden in deutscher Ortszeit geplant und auf Überschneidungen geprüft.", "Team members with editing permission can be assigned. Dates are scheduled in German local time and checked for overlaps."],
  ["Gib einem Betrieb oder Techniker zeitlich begrenzten Schreibzugriff nur auf diesen einen Pass. Der restliche Haushalt oder Firmenbereich bleibt unsichtbar.", "Give a company or technician time-limited write access to this pass only. The rest of the household or company workspace remains hidden."],
  ["Servicepartner-Zugang: Du kannst Service dokumentieren, aber keine Stammdaten, Dateien oder Freigaben des Objektpasses ändern.", "Service-provider access: You can document service work, but cannot change master data, files, or sharing settings for the asset pass."],
  ["Für einen Service- oder Wartungseintrag brauchst du mindestens die Rolle Bearbeiter oder einen aktiven Servicezugang für diese Anlage.", "A service or maintenance entry requires at least the Editor role or active service access for this asset."],
  ["Erfasse Arbeiten, Messwerte, Material und Feststellungen; anschließend unterschreibt der Kunde direkt auf dem Gerät.", "Record work, readings, materials, and findings; the customer can then sign directly on the device."],
  ["Ein Firmenprofil allein gibt keine Schreibrechte. Der Eigentümer muss entweder eine zeitlich begrenzte Servicefreigabe für einen einzelnen Pass erteilen oder dich als Bearbeiter eines gemeinsamen Bereichs berechtigen.", "A company profile alone does not grant write access. The owner must grant time-limited service access to a single pass or make you an editor in a shared workspace."],
  ["Privatnutzer verwalten ihre eigenen Objektpässe. Firmen und Techniker können sich mit Firmenbezeichnung ausweisen und berechtigte Wartungs- und Serviceeinträge direkt nach einem QR-Scan dokumentieren.", "Private users manage their own asset passes. Companies and technicians can identify their business and document authorized maintenance and service work immediately after scanning a QR code."],
  ["Wähle einen Objektpass aus, um dessen QR-Code als Druckvorlage zu öffnen oder wetterfeste QR-Aufkleber anzufragen.", "Select an asset pass to open its QR code as a print template or request weather-resistant QR stickers."],
  ["Für größere Bestände wählst du mehrere Objektpässe aus und sendest eine gemeinsame Anfrage. Jeder Pass erhält weiterhin seinen individuellen QR-Code; pro Gerät sind maximal 2 Aufkleber möglich.", "For larger inventories, select multiple asset passes and send one combined request. Every pass keeps its individual QR code; up to 2 stickers are available per asset."],
  ["Die Sammelanfrage erzeugt für jeden ausgewählten Objektpass eine eigene Bestellposition mit dessen individuellem QR-Code. Es wird weiterhin noch keine Zahlung ausgelöst; Preis und Produktion werden separat bestätigt.", "The combined request creates a separate item with an individual QR code for every selected asset pass. No payment is triggered yet; price and production are confirmed separately."],
  ["Pro ausgewähltem Objekt werden 1 oder optional 2 identische Aufkleber für genau diesen Objektpass angefragt. Bei 20 ausgewählten Geräten entstehen damit 20 verschiedene QR-Codes.", "For each selected asset, request 1 or optionally 2 identical stickers for that exact pass. Selecting 20 assets therefore creates 20 different QR codes."],
  ["Der Aufkleber verweist direkt auf diesen Objektpass. So kann der Pass später mit der Smartphone-Kamera oder dem NavoPass-Scanner direkt am Gerät geöffnet werden.", "The sticker links directly to this asset pass, allowing it to be opened at the asset with a phone camera or the NavoPass scanner."],
  ["NavoPass produziert keine Etiketten selbst. Die Anfrage wird gesammelt und anschließend über einen externen Druckdienstleister abgewickelt. Deshalb wird mit dem Absenden noch keine kostenpflichtige Bestellung ausgelöst.", "NavoPass does not produce labels itself. Requests are collected and fulfilled by an external print provider, so submitting the form does not create a paid order."],
  ["Durch Absenden wird nur eine Bestellanfrage an NavoPass übermittelt. Eine kostenpflichtige Bestellung entsteht erst nach separater Preisbestätigung.", "Submitting only sends an order request to NavoPass. A paid order is created only after separate price confirmation."],
  ["Ein Aufkleber reicht normalerweise aus. Optional kannst du einen zweiten als Reserve oder für eine zweite gut erreichbare Position am selben Gerät anfragen.", "One sticker is normally sufficient. You may request a second as a spare or for another accessible position on the same asset."],
  ["Löscht dein Konto und deine persönlichen Daten dauerhaft. Ein noch laufendes Stripe-Abo wird dabei zuerst beendet, damit nach der Kontolöschung keine weitere NavoPass-Abrechnung erfolgt.", "Permanently deletes your account and personal data. Any active Stripe subscription is ended first to prevent further NavoPass billing after deletion."],
  ["Lade deine Konto-, Pass-, Historien- und Dokument-Metadaten als JSON-Datei herunter.", "Download your account, pass, history, and document metadata as a JSON file."],
  ["Fotos, Rechnungen, Anleitungen und Prüfberichte bleiben direkt am Objektpass gespeichert.", "Photos, invoices, manuals, and inspection reports remain stored with the asset pass."],
  ["Duplizieren erstellt eine private Kopie im selben Bereich. Archivieren und Löschen sind nur für Inhaber oder Admins möglich.", "Duplicate creates a private copy in the same workspace. Only owners or admins can archive and delete."],
  ["Archivierte Pässe zählen mit, werden aber niemals automatisch gelöscht.", "Archived passes count toward the limit but are never deleted automatically."],
  ["Gezählt werden lokal hochgeladene Dateien; externe Links verbrauchen keinen Speicher.", "Locally uploaded files count toward storage; external links use no storage."],
  ["Offene Einladungen reservieren bereits einen Platz.", "Pending invitations already reserve a seat."],
  ["Persönlicher Bereich zählt nicht gegen dieses Limit.", "The personal workspace does not count toward this limit."],
  ["NavoPass zeigt Wartungs- und Garantiehinweise innerhalb dieses Zeitraums in der Benachrichtigungszentrale.", "NavoPass shows maintenance and warranty reminders within this period in the notification center."],
  ["In den nächsten sieben Tagen sind keine offenen oder laufenden Einsätze terminiert.", "No open or active jobs are scheduled for the next seven days."],
  ["Keine Objekte vorhanden, die du verwalten darfst. Dir zugewiesene Einsätze erscheinen trotzdem unten.", "There are no assets you can manage. Jobs assigned to you still appear below."],
  ["Ändere Suche oder Filter – oder lege einen neuen Objektpass an.", "Adjust your search or filters – or create a new asset pass."],
  ["Sobald du Pässe anlegst, Wartungen dokumentierst oder Dateien hochlädst, erscheint hier deine Chronik.", "Your timeline appears here as soon as you create passes, document maintenance, or upload files."],
  ["Wartungen, neue Dokumente und Änderungen an deinen Objektpässen chronologisch an einem Ort.", "Maintenance, new documents, and changes to your asset passes in one chronological view."],
  ["Starte mit den wichtigsten Daten. Fotos, Dokumente und Historieneinträge kannst du direkt danach ergänzen.", "Start with the essential data. Add photos, documents, and history entries immediately afterward."],
  ["Wichtige Hinweise, Besonderheiten, Zubehör oder andere Informationen", "Important notes, special features, accessories, or other information"],
  ["Die Historie des Passes wurde aktualisiert.", "The pass history has been updated."],
  ["Dieser Pass ist archiviert.", "This pass is archived."],
  ["Er bleibt im Bereich erhalten, ist aber öffentlich nicht mehr abrufbar.", "It remains in the workspace but is no longer publicly accessible."],
  ["Produktdaten noch nicht vollständig", "Product data is not complete yet"],
  ["Noch keine weiteren Anlagendaten", "No further asset data yet"],
  ["Noch keine Produktdaten", "No product data yet"],
  ["Noch keine weiteren Angaben", "No further details yet"],
  ["Noch keine Hinweise zum Zugang oder Standort hinterlegt.", "No access or location notes have been added yet."],
  ["Noch keine Ereignisse dokumentiert.", "No events documented yet."],
  ["Noch keine Fotos oder Dokumente gespeichert.", "No photos or documents saved yet."],
  ["Noch keine Kunden oder Standorte angelegt.", "No customers or locations created yet."],
  ["Noch keine verwaltbaren Objektpässe vorhanden.", "No manageable asset passes available yet."],
  ["Keine passenden Pässe.", "No matching passes."],
  ["Keine Einsätze in dieser Ansicht.", "No jobs in this view."],
  ["Keine offenen Serviceeinladungen.", "No pending service invitations."],
  ["Keine verwaltbaren Objektpässe", "No manageable asset passes"],
  ["Noch keine Aktivität.", "No activity yet."],
  ["Meine Pässe", "My passes"],
  ["Meine Einsätze", "My jobs"],
  ["Meine Daten exportieren", "Export my data"],
  ["Meine Aufkleber-Anfragen", "My sticker requests"],
  ["Kunden & Standorte", "Customers & locations"],
  ["Kunden & Anlagen", "Customers & assets"],
  ["Haushalte & Teams", "Households & teams"],
  ["Letzte Änderungen", "Recent changes"],
  ["Kontoaktivität", "Account activity"],
  ["Wartungszentrale", "Maintenance center"],
  ["Benachrichtigungen", "Notifications"],
  ["Einstellungen", "Settings"],
  ["Privat oder beruflich nutzen", "Personal or professional use"],
  ["NavoPass Profil", "NavoPass profile"],
  ["QR-Code scannen", "Scan QR code"],
  ["QR-Aufkleber als Sammelanfrage", "Combined QR sticker request"],
  ["QR-Aufkleber", "QR stickers"],
  ["Serviceaufträge", "Service jobs"],
  ["Einsatzplanung", "Job scheduling"],
  ["Wochenübersicht", "Weekly overview"],
  ["Auftragsliste", "Job list"],
  ["Heutige Einsätze", "Today’s jobs"],
  ["Einsätze der nächsten 7 Tage", "Jobs in the next 7 days"],
  ["Wartungen & Fristen", "Maintenance & deadlines"],
  ["Fristen & Einladungen", "Deadlines & invitations"],
  ["Fotos & Dokumente", "Photos & documents"],
  ["Service & Ereignisse", "Service & events"],
  ["Teilen & QR", "Sharing & QR"],
  ["Objektdaten", "Asset data"],
  ["Objektpass bearbeiten", "Edit asset pass"],
  ["Persönliche Daten", "Personal data"],
  ["Tarif & Nutzung", "Plan & usage"],
  ["Aktueller Tarif", "Current plan"],
  ["Gemeinsame Bereiche", "Shared workspaces"],
  ["Angemeldete Geräte", "Signed-in devices"],
  ["Fristen-Vorlauf", "Reminder window"],
  ["Passwort ändern", "Change password"],
  ["Export herunterladen", "Download export"],
  ["Gefahrenbereich", "Danger zone"],
  ["Konto löschen", "Delete account"],
  ["Konto endgültig löschen", "Permanently delete account"],
  ["Bereiche verwalten", "Manage workspaces"],
  ["Abo, Rechnungen & Zahlung verwalten", "Manage subscription, invoices & payment"],
  ["Tarife vergleichen", "Compare plans"],
  ["Mehr als Business benötigt? Kontakt aufnehmen", "Need more than Business? Contact us"],
  ["Profil speichern", "Save profile"],
  ["Erinnerungen speichern", "Save reminders"],
  ["Benachrichtigungen öffnen", "Open notifications"],
  ["Andere Geräte abmelden", "Sign out other devices"],
  ["Aktuelles Passwort", "Current password"],
  ["Neues Passwort wiederholen", "Repeat new password"],
  ["Neues Passwort", "New password"],
  ["E-Mail-Adresse", "Email address"],
  ["Nutzungsart", "Usage type"],
  ["Firma / Techniker / Servicebetrieb", "Company / technician / service provider"],
  ["Funktion / Qualifikation", "Role / qualification"],
  ["Firma / Techniker", "Company / technician"],
  ["Firma / Person", "Company / person"],
  ["Firma (optional)", "Company (optional)"],
  ["Kunde / Standort anlegen", "Create customer / location"],
  ["Kunde anlegen", "Create customer"],
  ["Kundendaten bearbeiten", "Edit customer data"],
  ["Kundendaten speichern", "Save customer data"],
  ["Kundendetails", "Customer details"],
  ["Objekt einem Kunden zuweisen", "Assign asset to customer"],
  ["Zuordnung speichern", "Save assignment"],
  ["Keine Zuordnung", "No assignment"],
  ["Ohne Kunde", "Without customer"],
  ["Alle Kunden & Standorte", "All customers & locations"],
  ["Kunde oder Standort filtern", "Filter customer or location"],
  ["Kunde / Objektbezeichnung", "Customer / asset name"],
  ["Ansprechpartner", "Contact person"],
  ["Straße & Hausnummer", "Street & house number"],
  ["Ort", "City"],
  ["Land", "Country"],
  ["Deutschland", "Germany"],
  ["Österreich", "Austria"],
  ["Schweiz", "Switzerland"],
  ["Polen", "Poland"],
  ["Einsatz anlegen", "Create job"],
  ["Einsatz starten", "Start job"],
  ["Serviceauftrag abschließen", "Complete service job"],
  ["Zurück auf offen", "Move back to open"],
  ["Geplante Dauer", "Planned duration"],
  ["Dauer ändern", "Change duration"],
  ["Mitarbeiter filtern", "Filter team member"],
  ["Alle Teammitglieder", "All team members"],
  ["Mitarbeiter / Servicekraft", "Employee / service technician"],
  ["Priorität", "Priority"],
  ["Dringend", "Urgent"],
  ["Niedrig", "Low"],
  ["Normal", "Normal"],
  ["Offen", "Open"],
  ["In Arbeit", "In progress"],
  ["Planung", "Planning"],
  ["Disposition", "Scheduling"],
  ["Planungsansicht", "Planning view"],
  ["Übersicht", "Overview"],
  ["Auftrag / Einsatz", "Job / assignment"],
  ["Auftragsnotiz", "Job note"],
  ["Zugewiesen", "Assigned"],
  ["Termin ändern", "Change date"],
  ["Termin überschritten", "Past due"],
  ["noch ungeplant", "not scheduled yet"],
  ["Vor Ort erfassen", "Record on site"],
  ["Direkt dokumentieren", "Document now"],
  ["Bericht erfassen", "Create report"],
  ["Bericht öffnen / senden", "Open / send report"],
  ["Bericht öffnen", "Open report"],
  ["Bericht an Kunden senden", "Send report to customer"],
  ["Geschützten Bericht senden", "Send protected report"],
  ["Versendete Bericht-Links", "Sent report links"],
  ["Link widerrufen", "Revoke link"],
  ["Zustellung", "Delivery"],
  ["Gesendet", "Sent"],
  ["Geöffnet", "Opened"],
  ["Widerrufen", "Revoked"],
  ["Abgelaufen", "Expired"],
  ["noch nicht geöffnet", "not opened yet"],
  ["Durchgeführte Arbeiten", "Work performed"],
  ["Verbaute Teile / Material", "Parts / materials used"],
  ["Mängel / Feststellungen", "Defects / findings"],
  ["Empfehlung / weitere Maßnahmen", "Recommendation / next steps"],
  ["Messwerte", "Measurements"],
  ["Arbeitszeit in Minuten", "Labor in minutes"],
  ["Arbeitszeit", "Labor"],
  ["Kosten €", "Cost €"],
  ["Kosten", "Cost"],
  ["Kundenname für Bestätigung", "Customer name for confirmation"],
  ["Kundenunterschrift", "Customer signature"],
  ["Techniker / ausführender Betrieb", "Technician / service company"],
  ["Techniker / Konto", "Technician / account"],
  ["Ausgeführt durch", "Performed by"],
  ["Anlage / Gerät", "Asset / device"],
  ["Nächste Wartung", "Next maintenance"],
  ["Nächster Service / Prüfung", "Next service / inspection"],
  ["Kauf / Installation", "Purchase / installation"],
  ["Kauf-/Installationsdatum", "Purchase / installation date"],
  ["Garantie bis", "Warranty until"],
  ["Wartungsintervall", "Maintenance interval"],
  ["Nächsten Wartungstermin berechnen", "Calculate next maintenance date"],
  ["Servicezugriff verwalten", "Manage service access"],
  ["Servicepartner einladen", "Invite service provider"],
  ["Freigegebene Servicepartner", "Authorized service providers"],
  ["Noch nicht angenommene Einladungen", "Pending invitations"],
  ["Neue Freigabe", "New access grant"],
  ["Zugriffsdauer", "Access duration"],
  ["Zugriff widerrufen", "Revoke access"],
  ["Einladung zurückziehen", "Withdraw invitation"],
  ["Servicefreigabe senden", "Send service access invitation"],
  ["Druckvorlage", "Print template"],
  ["Dein QR-Code", "Your QR code"],
  ["QR-Code öffnen / speichern", "Open / save QR code"],
  ["Bestellanfrage", "Order request"],
  ["Aufkleber konfigurieren", "Configure stickers"],
  ["Stückzahl", "Quantity"],
  ["Stück", "item"],
  ["Größe", "Size"],
  ["Ausführung", "Finish"],
  ["Wetterfest matt", "Weather-resistant matte"],
  ["Wetterfest glänzend", "Weather-resistant gloss"],
  ["Empfänger", "Recipient"],
  ["Hinweis (optional)", "Note (optional)"],
  ["Noch keine Zahlung", "No payment yet"],
  ["QR-Aufkleber anfragen", "Request QR stickers"],
  ["Sammelanfrage absenden", "Submit combined request"],
  ["Objekte auswählen", "Select assets"],
  ["Aufkleber je Objekt", "Stickers per asset"],
  ["Viele Geräte, viele eigene QR-Codes", "Many assets, many individual QR codes"],
  ["Mehrere Geräte · getrennte QR-Codes", "Multiple assets · separate QR codes"],
  ["Anfragen", "Requests"],
  ["Letzter Status", "Latest status"],
  ["Angefragt", "Requested"],
  ["Bestätigt", "Confirmed"],
  ["In Produktion", "In production"],
  ["Versendet", "Shipped"],
  ["Storniert", "Cancelled"],
  ["Hersteller", "Manufacturer"],
  ["Modell / Typ", "Model / type"],
  ["Modell", "Model"],
  ["Serien-, Geräte- oder Inventarnummer", "Serial, device, or inventory number"],
  ["Seriennummer", "Serial number"],
  ["Standort", "Location"],
  ["Kategorie", "Category"],
  ["Bezeichnung", "Name"],
  ["Beschreibung", "Description"],
  ["Notizen", "Notes"],
  ["Sichtbarkeit", "Visibility"],
  ["Privat – nur Mitglieder", "Private – members only"],
  ["Per Link/QR – wer den Link hat", "By link/QR – anyone with the link"],
  ["Per Link / QR", "By link / QR"],
  ["Öffentlich", "Public"],
  ["Privat", "Private"],
  ["Persönlich", "Personal"],
  ["Bearbeiter", "Editor"],
  ["Betrachter", "Viewer"],
  ["Inhaber", "Owner"],
  ["Nur Lesezugriff", "Read-only access"],
  ["Nur ansehen", "View only"],
  ["Bearbeiten", "Edit"],
  ["Stammdaten bearbeiten", "Edit master data"],
  ["Änderungen speichern", "Save changes"],
  ["Speichern", "Save"],
  ["Löschen", "Delete"],
  ["Abbrechen", "Cancel"],
  ["Entfernen", "Remove"],
  ["Öffnen", "Open"],
  ["Pass öffnen", "Open pass"],
  ["Pass ansehen", "View pass"],
  ["Pass verwalten", "Manage pass"],
  ["Pass duplizieren", "Duplicate pass"],
  ["Pass archivieren", "Archive pass"],
  ["Pass löschen", "Delete pass"],
  ["Objektpass anlegen", "Create asset pass"],
  ["Neues Objekt", "New asset"],
  ["Name des Objekts", "Asset name"],
  ["Pässe durchsuchen", "Search passes"],
  ["Alle Bereiche", "All workspaces"],
  ["Alle Kategorien", "All categories"],
  ["Aktive Pässe", "Active passes"],
  ["Aktivität", "Activity"],
  ["Zuletzt geändert", "Last updated"],
  ["Favorit entfernen", "Remove favorite"],
  ["Als Favorit", "Add to favorites"],
  ["Favorit", "Favorite"],
  ["Wartung durchgeführt", "Maintenance completed"],
  ["Wartung eintragen", "Add maintenance"],
  ["Wartung hinterlegen", "Add maintenance"],
  ["Wartung erledigt", "Maintenance complete"],
  ["Wartung", "Maintenance"],
  ["Wartungen", "Maintenance"],
  ["Garantie", "Warranty"],
  ["Prüfung / Inspektion", "Check / inspection"],
  ["Prüfung", "Inspection"],
  ["Reparatur", "Repair"],
  ["Notiz", "Note"],
  ["Ereignis hinzufügen", "Add event"],
  ["Datei hochladen", "Upload file"],
  ["Link hinzufügen", "Add link"],
  ["Dokument", "Document"],
  ["Unterlagen", "Documents"],
  ["Rechnung", "Invoice"],
  ["Anleitung", "Manual"],
  ["Prüfbericht", "Inspection report"],
  ["Foto", "Photo"],
  ["Datei", "File"],
  ["Titel (optional)", "Title (optional)"],
  ["Im geteilten Pass sichtbar", "Visible in shared pass"],
  ["Lokal gespeichert", "Stored locally"],
  ["PDF oder Foto bis 15 MB. HEIC/HEIF vom iPhone wird ebenfalls akzeptiert.", "PDF or photo up to 15 MB. HEIC/HEIF from iPhone is also supported."],
  ["Noch nicht gesetzt", "Not set yet"],
  ["Demnächst fällig", "Due soon"],
  ["Überfällig", "Overdue"],
  ["Läuft bald aus", "Expires soon"],
  ["Aktiv", "Active"],
  ["Eintrag", "entry"],
  ["Einträge", "entries"],
  ["Monate", "months"],
  ["Monat", "month"],
  ["Jahr", "year"],
  ["Tage", "days"],
  ["Tag", "day"],
  ["Stunden", "hours"],
  ["Minuten", "minutes"],
  ["Datum", "Date"],
  ["Titel", "Title"],
  ["Typ", "Type"],
  ["Rolle", "Role"],
  ["Bereich", "Workspace"],
  ["Nutzer", "Users"],
  ["Nutzerplätze", "Seats"],
  ["Pässe", "Passes"],
  ["Speicher", "Storage"],
  ["Daten", "Data"],
  ["Sicherheit", "Security"],
  ["Sitzungen", "Sessions"],
  ["Profil", "Profile"],
  ["Erinnerungen", "Reminders"],
  ["Zusammenarbeit", "Collaboration"],
  ["Chronik", "Timeline"],
  ["Verlauf", "History"],
  ["Hinweise", "Notes"],
  ["Vor-Ort-Hinweise", "On-site notes"],
  ["Weitere Aktionen", "More actions"],
  ["Zurück zu den Tarifen", "Back to plans"],
  ["Zurück zu", "Back to"],
  ["Zum Objektpass", "Asset pass"],
  ["Meine Pässe", "My passes"],
];

const patterns: Array<[RegExp, string]> = [
  [/^(\d+) Tage vorher$/, "$1 days before"],
  [/^(\d+) Monate Intervall$/, "$1-month interval"],
  [/^(\d+) Monate$/, "$1 months"],
  [/^(\d+) Stunden$/, "$1 hours"],
  [/^(\d+) Minuten$/, "$1 minutes"],
  [/^gültig bis$/, "valid until"],
  [/^Einladung bis$/, "Invitation until"],
  [/^Zugriff vorgesehen bis$/, "Access planned until"],
  [/^Gespeichert am$/, "Saved on"],
  [/^Status:\s*$/, "Status: "],
  [/^Intervall:\s*$/, "Interval: "],
];

const exactTranslations = new Map(translations);

function translate(value: string) {
  const trimmed = value.trim();
  const exact = exactTranslations.get(trimmed);
  if (exact) return value.replace(trimmed, exact);
  for (const [pattern, replacement] of patterns) {
    const translated = trimmed.replace(pattern, replacement);
    if (translated !== trimmed) return value.replace(trimmed, translated);
  }
  return value;
}

function translateTree(root: HTMLElement) {
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  const nodes: Text[] = [];
  while (walker.nextNode()) nodes.push(walker.currentNode as Text);
  for (const node of nodes) {
    const next = translate(node.data);
    if (next !== node.data) node.data = next;
  }
  for (const element of root.querySelectorAll<HTMLElement>("[placeholder], [aria-label], [title]")) {
    for (const attribute of ["placeholder", "aria-label", "title"]) {
      const value = element.getAttribute(attribute);
      if (value) {
        const next = translate(value);
        if (next !== value) element.setAttribute(attribute, next);
      }
    }
  }
}

export function AppEnglishLayer({ enabled, children }: { enabled: boolean; children: ReactNode }) {
  const rootRef = useRef<HTMLDivElement>(null);
  const [ready, setReady] = useState(!enabled);

  useLayoutEffect(() => {
    const root = rootRef.current;
    if (!enabled || !root) return;
    let queued = false;
    const run = () => {
      queued = false;
      translateTree(root);
      setReady(true);
    };
    run();
    const observer = new MutationObserver(() => {
      if (!queued) {
        queued = true;
        queueMicrotask(run);
      }
    });
    observer.observe(root, { childList: true, subtree: true, characterData: true, attributes: true, attributeFilter: ["placeholder", "aria-label", "title"] });
    return () => observer.disconnect();
  }, [enabled]);

  return <div ref={rootRef} style={{ visibility: ready ? "visible" : "hidden" }}>{children}</div>;
}
