import Link from "next/link";
import { NavoPassContactForm } from "@/components/navopass-contact-form";
import { PublicShell } from "@/components/public-shell";
import styles from "@/app/public-pages.module.css";

function LegalLinks() {
  return <nav className={styles.legalLinks} aria-label="More legal information"><Link href="/impressum">Legal notice</Link><Link href="/datenschutz">Privacy</Link><Link href="/nutzungsbedingungen">Terms of use</Link><Link href="/preise">Pricing</Link><Link href="/vertrag-widerrufen">Withdraw from contract</Link><Link href="/vertrag-kuendigen">Cancel subscription</Link><Link href="/kontakt">Contact</Link></nav>;
}

export function EnglishImprint() {
  return <PublicShell><main className={styles.main}>
    <section className={styles.hero}><span className={styles.eyebrow}>Legal information</span><h1>Legal notice</h1><p>Provider information pursuant to Section 5 of the German Digital Services Act (DDG) for the NavoPass digital service.</p></section>
    <article className={styles.legal}>
      <section><h2>Service provider</h2><p><strong>Piotr Kaminski – Kamilunavo</strong><br />Sole proprietorship<br />Otto-Braun-Straße 14<br />40595 Düsseldorf<br />Germany</p></section>
      <section><h2>Contact</h2><p>Email: <a href="mailto:contact@kamilunavo.com">contact@kamilunavo.com</a><br />Phone: <a href="tel:+4915114082801">+49 151 14082801</a></p><div className={styles.methods}><div className={styles.method}><span>Direct contact</span><a href="mailto:contact@kamilunavo.com">contact@kamilunavo.com</a></div><div className={styles.method}><span>Phone</span><a href="tel:+4915114082801">+49 151 14082801</a></div><div className={styles.method}><span>Additional electronic contact method</span><b>Contact form below</b></div></div><NavoPassContactForm locale="en" /></section>
      <section><h2>Registers and identification numbers</h2><p>There is currently no entry in the commercial register.</p><p>German business identification number pursuant to Section 139c of the Fiscal Code: <strong>DE464473083-00001</strong></p><p>No VAT identification number pursuant to Section 27a of the German VAT Act has currently been issued.</p></section>
      <section><h2>Consumer dispute resolution</h2><p>We are neither willing nor obliged to participate in dispute resolution proceedings before a consumer arbitration board.</p><p>A link to the former EU online dispute resolution platform is no longer provided because the platform has been discontinued and its underlying EU regulation repealed.</p></section>
      <section><h2>Content and copyright</h2><p>Texts, designs, graphics, logos, product names and other NavoPass content are protected under applicable law. Any use beyond statutory limitations requires the prior consent of the respective rights holder.</p></section>
      <LegalLinks /><p className={styles.meta}>Last updated: 31 August 2026</p>
    </article>
  </main></PublicShell>;
}

export function EnglishPrivacy() {
  return <PublicShell><main className={styles.main}>
    <section className={styles.hero}><span className={styles.eyebrow}>Privacy</span><h1>Privacy policy</h1><p>Information about the processing of personal data on navopass.de and when using the NavoPass digital service.</p></section>
    <article className={styles.legal}>
      <section><h2>1. Controller</h2><p><strong>Piotr Kaminski – Kamilunavo</strong><br />Otto-Braun-Straße 14<br />40595 Düsseldorf<br />Germany<br />Email: <a href="mailto:contact@kamilunavo.com">contact@kamilunavo.com</a></p></section>
      <section><h2>2. Website delivery, server logs and language selection</h2><p>When navopass.de is accessed, technically necessary connection data may be processed, including the IP address, date and time, requested URL, referrer, browser and operating-system information, HTTP status code and transferred data volume.</p><p>This processing is necessary to deliver the service, maintain stability and security, and detect or prevent misuse. The legal basis is Article 6(1)(f) GDPR.</p><p>To show German to visitors in Germany and English elsewhere, NavoPass first uses a country code supplied by the upstream network. If none is available, the IP address may be sent once to the IP-to-country service <a href="https://country.is/" target="_blank" rel="noreferrer">Country</a>. Only the two-letter country code is used and stored for up to 24 hours in the <code className={styles.legalCode}>navopass_country</code> cookie. According to the provider, the service requires no key and does not log requests. If lookup fails, the browser language is used as a fallback. The legal basis is Article 6(1)(f) GDPR; the legitimate interest is providing an understandable, location-appropriate international service.</p></section>
      <section><h2>3. Hosting</h2><p>NavoPass runs on infrastructure provided by Hetzner Online GmbH, Industriestr. 25, 91710 Gunzenhausen, Germany. Data required for operation, databases, file storage and technical logging is processed there. Where required, processing is governed by a data processing agreement.</p></section>
      <section><h2>4. Registration, email verification and user accounts</h2><p>Registration processes your name, email address and password. Passwords are stored only as cryptographic hashes. This data is required to provide the account, enable sign-in and perform the NavoPass contract. The legal basis is Article 6(1)(b) GDPR.</p><p>Email verification uses a time-limited, single-use link; only a cryptographic hash of the token is stored. If the account email changes, the new address must be verified again. NavoPass also records the acceptance time and version of the Terms of use and the time the Privacy policy was acknowledged.</p></section>
      <section><h2>5. Sign-in, password recovery and necessary cookies</h2><p>Signed-in users receive the necessary <code className={styles.legalCode}>navopass_session</code> cookie containing a random session token; only its hash is stored server-side. Sessions generally expire after 30 days and can be ended sooner by signing out.</p><p>Language selection uses <code className={styles.legalCode}>navopass_country</code> for the detected country code (up to 24 hours) and, after a manual selection, <code className={styles.legalCode}>navopass_locale</code> (up to one year). Neither cookie contains account or content data.</p><p>Password recovery processes the submitted email address. If an account exists, NavoPass creates a time-limited, single-use recovery link and stores only the token hash. Existing sessions end after a successful password change.</p></section>
      <section><h2>6. Asset passes, history and documents</h2><p>NavoPass processes the asset and product information entered by users, such as name, category, manufacturer, model, serial number, location, purchase or installation date, warranty and maintenance data, notes, and service or repair histories.</p><p>Uploaded photos and documents are stored on NavoPass infrastructure and linked to the relevant pass. Users decide which content they upload. The legal basis is Article 6(1)(b) GDPR.</p></section>
      <section><h2>7. Sharing links and QR codes</h2><p>Users may set a pass to private, accessible by link/QR, or public. Shared pass data and history entries or documents explicitly marked as shared may then be accessible to others. QR codes are generated within NavoPass without an external QR provider. Private passes cannot be accessed through the public pass link.</p></section>
      <section><h2>8. Household and team workspaces</h2><p>Shared workspaces process the workspace name, memberships, roles and invited email addresses. Depending on their role, members can view or edit passes. The legal basis is Article 6(1)(b) GDPR. Invitations may include the inviter’s name, workspace, role and a time-limited invitation link. The invited account must verify its email before joining.</p></section>
      <section><h2>9. Maintenance, deadlines and calendar export</h2><p>NavoPass processes stored maintenance and warranty dates to display them and generate calendar files. Calendar exports are created directly by NavoPass. Importing them into an external calendar may result in additional processing by that provider.</p></section>
      <section><h2>10. Email and contact form</h2><p>When you contact us, we process the sender address, message and voluntarily supplied contact details to answer the enquiry. Article 6(1)(b) GDPR applies to contractual or pre-contractual matters; otherwise Article 6(1)(f) GDPR applies.</p><p>The contact form sends the name, email, topic and message to the NavoPass server for validation and then forwards it through the configured business email infrastructure.</p></section>
      <section><h2>11. Email and domain infrastructure</h2><p>Services of One.com Group AB, Carlsgatan 3, 211 20 Malmö, Sweden may be used for domain management, DNS and business email. This includes support, verification, recovery, invitation, contract confirmation, cancellation and withdrawal emails.</p></section>
      <section><h2>12. Paid plans, contract records and Stripe</h2><p>Stripe is used to purchase and manage paid subscriptions. Payment details are entered in Stripe Checkout or Stripe payment interfaces; NavoPass does not store complete card numbers. NavoPass stores identifiers and subscription data needed to associate and perform the contract, including Stripe customer, subscription and Price IDs, subscription status, billing period and cancellation status.</p><p>Before checkout, NavoPass records the chosen plan and billing period, accepted Terms version, acknowledgement of withdrawal information and any express request for early performance. After checkout, a contract confirmation is emailed and its dispatch recorded.</p><p>Stripe may process contact, transaction, payment, IP and device data for payment processing, fraud prevention, billing and legal obligations. The legal bases for processing initiated by Kamilunavo are Article 6(1)(b) and, where legally required, Article 6(1)(c) GDPR. Stripe provides further information in its <a href="https://stripe.com/privacy" target="_blank" rel="noreferrer">Privacy policy</a> and <a href="https://stripe.com/en-de/legal/privacy-center" target="_blank" rel="noreferrer">Privacy Center</a>.</p></section>
      <section><h2>13. Electronic cancellation and withdrawal</h2><p>Cancellation and withdrawal declarations can be submitted electronically without signing in. NavoPass processes the information required to identify and document the request, including contact and contract details, the requested ending, reasons where applicable, timestamps, processing and confirmation status. Random confirmation links are created and only their hashes are stored. The legal bases are Article 6(1)(b) and (c) GDPR.</p></section>
      <section><h2>14. Analytics, advertising and profiling</h2><p>NavoPass currently uses no proprietary marketing or analytics cookies, Google Analytics, Meta Pixel or proprietary advertising profiling. If this changes, this policy will be updated and any required consent obtained beforehand.</p></section>
      <section><h2>15. Recipients and international transfers</h2><p>Data is disclosed only where necessary for operation, contract performance, payment, user-directed sharing or legal obligations. Recipients may include hosting, email and payment providers, invited workspace members, or recipients of a sharing link.</p><p>Stripe-related processing may take place outside the EEA depending on the payment method and Stripe infrastructure. Stripe describes applicable transfer mechanisms and safeguards in its privacy information.</p></section>
      <section><h2>16. Retention</h2><p>Account data and NavoPass content are generally retained for the life of the account or until the respective content is deleted. Sessions normally expire after 30 days; unused verification and recovery tokens are time-limited.</p><p>Billing, contract, consent, cancellation and withdrawal records may be retained beyond account deletion where required by statutory retention periods, tax duties, contract handling or legal claims. Stripe retains payment and billing data under its applicable legal and contractual rules.</p></section>
      <section><h2>17. Data subject rights</h2><p>Subject to statutory requirements, you may have rights of access, rectification, erasure, restriction, portability and objection. Consent can be withdrawn for the future. Requests can be sent to <a href="mailto:contact@kamilunavo.com">contact@kamilunavo.com</a>.</p><p>You may also complain to a supervisory authority. The competent authority for Kamilunavo’s location is the <a href="https://www.ldi.nrw.de/" target="_blank" rel="noreferrer">State Commissioner for Data Protection and Freedom of Information North Rhine-Westphalia</a>.</p></section>
      <section><h2>18. Automated decisions</h2><p>NavoPass currently performs no automated decision-making within Article 22 GDPR and no proprietary profiling. Stripe may use automated measures for payment and fraud prevention as described in its privacy information.</p></section>
      <section><h2>19. Changes to this policy</h2><p>This policy is updated when features, providers or legal requirements change. The version published on navopass.de applies.</p></section>
      <LegalLinks /><p className={styles.meta}>Last updated: 3 September 2026</p>
    </article>
  </main></PublicShell>;
}

export function EnglishTerms() {
  return <PublicShell><main className={styles.main}>
    <section className={styles.hero}><span className={styles.eyebrow}>NavoPass terms</span><h1>Terms of use</h1><p>These terms govern registration and the free or paid use of the NavoPass digital service.</p></section>
    <article className={styles.legal}>
      <section><h2>1. Provider and scope</h2><p>NavoPass is provided by Piotr Kaminski – Kamilunavo, Otto-Braun-Straße 14, 40595 Düsseldorf, Germany. These terms apply to user accounts and use of navopass.de. Mandatory statutory rights, particularly consumer rights, remain unaffected.</p></section>
      <section><h2>2. Registration and user account</h2><p>An account is required for protected features. Users must provide accurate information, use a reachable email address and protect their credentials. Email verification may be required for security-sensitive features and shared workspaces.</p><p>The free contract begins when registration is completed and the account is provided. A free account never becomes paid merely through time or use.</p></section>
      <section><h2>3. Plans, prices and paid orders</h2><p>NavoPass offers free and paid plans. Features, limits and prices for each billing period are shown on the <Link href="/preise">Pricing</Link> page and immediately before purchase.</p><p>A paid order requires an express choice. Before Stripe Checkout, the plan, interval, essential features, cancellation terms and withdrawal information are shown and confirmed again. The subscription activates only after successful checkout and server-side confirmation. The total displayed by Stripe immediately before purchase controls. No shipping fees apply.</p></section>
      <section><h2>4. Billing interval, term and renewal</h2><p>Paid plans are billed monthly or annually in advance. The subscription continues until cancelled or otherwise ended; a new billing period begins unless it is cancelled.</p><p>Ordinary cancellation is possible at the end of the current billing period. The specific ending appears in the account or Stripe customer portal. Statutory withdrawal and special termination rights remain unaffected.</p></section>
      <section><h2>5. Payment and Stripe</h2><p>Stripe handles payments and billing. Available payment methods are shown in Checkout. NavoPass stores no complete card numbers. If payment fails, Stripe may retry or request an updated payment method. Paid access may be restricted according to the confirmed subscription status, but existing NavoPass data is not automatically deleted solely because of a plan restriction.</p></section>
      <section><h2>6. Features and plan limits</h2><p>NavoPass supports digital asset passes, product information, photos, documents, history, maintenance and warranty deadlines, calendar exports, and collaboration in personal, household and team workspaces.</p><p>Plans may limit passes, storage, seats and shared workspaces. If a downgrade leaves the account above a limit, existing data generally remains available, while new passes, uploads, members or workspaces may be blocked until the account is within its current limits or upgraded.</p></section>
      <section><h2>7. Start of paid service and withdrawal</h2><p>Consumers generally have a statutory right of withdrawal for paid distance contracts. Details, the withdrawal notice and the electronic <Link href="/vertrag-widerrufen">Withdraw from contract</Link> function remain available online.</p><p>Before checkout, users who want paid functions immediately are expressly asked whether performance should begin before the withdrawal period expires. Any consequences of later withdrawal, including statutory compensation for service already provided at the consumer’s express request, are governed exclusively by law.</p></section>
      <section><h2>8. Cancellation and contract management</h2><p>Signed-in users can manage subscriptions through the linked Stripe customer portal. The <Link href="/vertrag-kuendigen">Cancel subscription</Link> function is also permanently available without signing in.</p><p>An ordinary cancellation for the next possible date is scheduled automatically for the end of the current billing period when the Stripe subscription can be identified unambiguously. Other requested endings and extraordinary cancellations are recorded with their content and timestamp and processed under contractual and statutory requirements. Receipt is confirmed electronically.</p></section>
      <section><h2>9. Plan changes</h2><p>Changes to an existing paid plan or billing interval use the provided Stripe or NavoPass functions. Applicable prices and billing consequences are displayed before the change. The normal change flow is not intended to create a parallel second NavoPass subscription.</p></section>
      <section><h2>10. User content and rights</h2><p>Users retain their rights in uploaded or entered content. They grant Kamilunavo only the technical rights required to store, process and display it and, where enabled by the user, make it accessible through sharing links or QR codes.</p><p>Users may upload or share only content for which they hold the necessary rights and whose processing does not violate law or third-party rights.</p></section>
      <section><h2>11. Sharing, QR codes and workspaces</h2><p>Users control pass visibility. “By link / QR” permits access by anyone with the link; “Public” may permit access without signing in. Restrictive visibility should be chosen for confidential or personal data. In shared workspaces, assigned roles control viewing, editing and administration. Workspace owners are responsible for appropriate invitations and roles.</p></section>
      <section><h2>12. Prohibited use</h2><p>Prohibited activities include unlawful content, malware, infrastructure attacks, bypassing security, disruptive automated access, spam, misuse of third-party data and actions that impair NavoPass stability or security.</p></section>
      <section><h2>13. Availability, maintenance and changes</h2><p>Kamilunavo aims to operate NavoPass reliably but cannot guarantee uninterrupted availability. Maintenance, security measures, technical faults or events beyond its control may temporarily restrict use. Features may evolve; statutory requirements apply to changes affecting ongoing consumer contracts and digital products.</p></section>
      <section><h2>14. Deadlines and reminders</h2><p>Maintenance, warranty and other deadline functions are organisational aids. Users remain responsible for verifying entered data and monitoring legally or technically relevant deadlines. NavoPass does not replace mandatory inspections, professional maintenance or binding manufacturer information.</p></section>
      <section><h2>15. Account deletion</h2><p>The account can be deleted in Settings once any shared workspaces requiring cleanup have been resolved. If an active NavoPass subscription exists, NavoPass attempts to end it through Stripe first. If that fails technically, deletion is stopped so that no active subscription remains without an associated account. Statutory retention, billing, refund and evidence duties remain unaffected.</p></section>
      <section><h2>16. Liability</h2><p>Liability is governed by law. For slight negligence involving an essential contractual duty, liability is limited, where legally permissible, to foreseeable damage typical of the contract. Intent, gross negligence, injury to life, body or health and mandatory statutory liability remain unaffected.</p></section>
      <section><h2>17. Privacy</h2><p>Information about personal data processing, including Stripe payment processing, is provided in the <Link href="/datenschutz">Privacy policy</Link>.</p></section>
      <section><h2>18. Consumer dispute resolution</h2><p>Kamilunavo is neither willing nor obliged to participate in dispute resolution before a consumer arbitration board. The former EU online dispute resolution platform has been discontinued, so no outdated ODR link is provided.</p></section>
      <section><h2>19. Governing law</h2><p>German law applies, excluding the UN Convention on Contracts for the International Sale of Goods. For consumers, this choice applies only insofar as it does not remove protection under mandatory rules of their habitual country of residence. Statutory jurisdiction rules remain unaffected.</p></section>
      <section><h2>20. Changes to these terms</h2><p>These terms may be updated if NavoPass or the legal framework changes. Existing contracts are changed only within statutory requirements. A free plan does not automatically become paid without a new express paid order.</p></section>
      <LegalLinks /><p className={styles.meta}>Last updated: 17 August 2026 · Version 2026-08-17-paid-v1</p>
    </article>
  </main></PublicShell>;
}
