"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { completeServiceAction, rescheduleServiceAction } from "@/app/actions/assets";
import type { Asset } from "@/lib/assets";
import { dateOnly, dateOnlyAsDate, daysUntil } from "@/lib/date";

type DeadlineKind="SERVICE"|"WARRANTY";
type Deadline={id:string;kind:DeadlineKind;date:string;days:number;asset:Asset};
type CustomerOption={id:string;name:string;city:string|null};

function formatDate(value:string){const parsed=dateOnlyAsDate(value);return parsed?new Intl.DateTimeFormat("de-DE",{dateStyle:"medium"}).format(parsed):"—";}
function relativeLabel(days:number){if(days<0)return `${Math.abs(days)} ${Math.abs(days)===1?"Tag":"Tage"} überfällig`;if(days===0)return"Heute fällig";if(days===1)return"Morgen fällig";return`in ${days} Tagen`;}
function tone(days:number){if(days<0)return"danger";if(days<=30)return"warning";return"ok";}
function editable(asset:Asset){return asset.access_role!=="VIEWER";}

export function ServiceCenterClient({assets,customers=[],customerByAsset={}}:{assets:Asset[];customers?:CustomerOption[];customerByAsset?:Record<string,string>}){
 const[scope,setScope]=useState("ALL"),[kind,setKind]=useState("ALL"),[query,setQuery]=useState(""),[customerId,setCustomerId]=useState("ALL");
 const customerNameById=useMemo(()=>new Map(customers.map(customer=>[customer.id,customer.name])),[customers]);
 const active=useMemo(()=>assets.filter(a=>!a.archived_at),[assets]);
 const customerMatches=(asset:Asset)=>customerId==="ALL"||(customerId==="UNASSIGNED"?!customerByAsset[asset.id]:customerByAsset[asset.id]===customerId);
 const deadlines=useMemo<Deadline[]>(()=>{const r:Deadline[]=[];for(const asset of active){const serviceDate=dateOnly(asset.next_service_date);const serviceDays=daysUntil(asset.next_service_date);if(serviceDate&&serviceDays!==null)r.push({id:`${asset.id}-service`,kind:"SERVICE",date:serviceDate,days:serviceDays,asset});const warrantyDate=dateOnly(asset.warranty_until);const warrantyDays=daysUntil(asset.warranty_until);if(warrantyDate&&warrantyDays!==null)r.push({id:`${asset.id}-warranty`,kind:"WARRANTY",date:warrantyDate,days:warrantyDays,asset});}return r.sort((a,b)=>a.days-b.days);},[active]);
 const visibleDeadlines=deadlines.filter(item=>customerMatches(item.asset));
 const unplanned=active.filter(a=>!dateOnly(a.next_service_date)&&customerMatches(a));
 const overdue=visibleDeadlines.filter(i=>i.days<0).length,next30=visibleDeadlines.filter(i=>i.days>=0&&i.days<=30).length,next90=visibleDeadlines.filter(i=>i.days>30&&i.days<=90).length;
 const filtered=visibleDeadlines.filter(item=>{if(kind!=="ALL"&&item.kind!==kind)return false;if(scope==="OVERDUE"&&item.days>=0)return false;if(scope==="30"&&(item.days<0||item.days>30))return false;if(scope==="90"&&(item.days<0||item.days>90))return false;const needle=query.trim().toLowerCase();const customerName=customerNameById.get(customerByAsset[item.asset.id]||"");return !needle||[item.asset.name,item.asset.category,item.asset.manufacturer,item.asset.model,item.asset.location,item.asset.workspace_name,customerName].filter(Boolean).some(v=>String(v).toLowerCase().includes(needle));});
 const resetFilters=()=>{setScope("ALL");setKind("ALL");setCustomerId("ALL");setQuery("");};
 const customerLabel=(asset:Asset)=>customerNameById.get(customerByAsset[asset.id]||"");
 return <><section className="service-stats"><button className={scope==="OVERDUE"?"active danger":"danger"} type="button" onClick={()=>setScope("OVERDUE")}><span>Überfällig</span><b>{overdue}</b><small>Sofort prüfen</small></button><button className={scope==="30"?"active warning":"warning"} type="button" onClick={()=>setScope("30")}><span>Nächste 30 Tage</span><b>{next30}</b><small>Wartung & Garantie</small></button><button className={scope==="90"?"active":""} type="button" onClick={()=>setScope("90")}><span>Nächste 90 Tage</span><b>{next90}</b><small>Vorausschau</small></button><button className={scope==="UNPLANNED"?"active":""} type="button" onClick={()=>setScope("UNPLANNED")}><span>Ohne Wartung</span><b>{unplanned.length}</b><small>Noch kein Termin</small></button></section>
 <section className="service-toolbar"><div className="search-field"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Objekte, Kunden und Fristen suchen…" /></div>{customers.length>0&&<select value={customerId} onChange={e=>setCustomerId(e.target.value)} aria-label="Kunde oder Standort filtern"><option value="ALL">Alle Kunden & Standorte</option>{customers.map(customer=><option value={customer.id} key={customer.id}>{customer.name}{customer.city?` · ${customer.city}`:""}</option>)}<option value="UNASSIGNED">Ohne Kundenzuordnung</option></select>}<div className="segmented"><button className={kind==="ALL"?"active":""} type="button" onClick={()=>setKind("ALL")}>Alle</button><button className={kind==="SERVICE"?"active":""} type="button" onClick={()=>setKind("SERVICE")}>Wartungen</button><button className={kind==="WARRANTY"?"active":""} type="button" onClick={()=>setKind("WARRANTY")}>Garantien</button></div><button className="button ghost small" type="button" onClick={resetFilters}>Filter zurücksetzen</button><a className="button small" href="/api/calendar">Kalender exportieren</a></section>
 {scope==="UNPLANNED"?<section className="service-list">{unplanned.length===0?<div className="empty-state compact"><div className="empty-icon">✓</div><h2>Alles geplant.</h2><p>Für die aktuelle Auswahl haben alle aktiven Pässe einen nächsten Wartungstermin.</p></div>:unplanned.map(asset=><article className="service-card neutral" key={asset.id}><div className="service-date"><span>—</span><b>Kein Termin</b><small>{asset.service_interval_months||12} Monate Intervall</small></div><div className="service-main"><span className="asset-category">{asset.category}</span><h2><Link href={`/app/assets/${asset.id}`}>{asset.name}</Link></h2><p>{[customerLabel(asset),asset.manufacturer,asset.model,asset.location,asset.workspace_name].filter(Boolean).join(" · ")||"Noch keine weiteren Angaben"}</p></div>{editable(asset)?<form action={rescheduleServiceAction} className="service-quick-form"><input type="hidden" name="assetId" value={asset.id}/><label>Erste Wartung<input name="nextServiceDate" type="date" required/></label><button className="button small" type="submit">Termin setzen</button></form>:<span className="access-chip">Nur ansehen</span>}</article>)}</section>:<section className="service-list">{filtered.length===0?<div className="empty-state compact"><div className="empty-icon">✓</div><h2>Keine passenden Fristen.</h2><p>Für diesen Zeitraum und Filter ist aktuell nichts fällig.</p></div>:filtered.map(item=><article className={`service-card ${tone(item.days)}`} key={item.id}><div className="service-date"><span>{item.kind==="SERVICE"?"Wartung":"Garantie"}</span><b>{formatDate(item.date)}</b><small>{relativeLabel(item.days)}</small></div><div className="service-main"><span className="asset-category">{item.asset.category}</span><h2><Link href={`/app/assets/${item.asset.id}`}>{item.asset.name}</Link></h2><p>{[customerLabel(item.asset),item.asset.manufacturer,item.asset.model,item.asset.location,item.asset.workspace_name].filter(Boolean).join(" · ")||"Noch keine weiteren Angaben"}</p>{item.kind==="SERVICE"&&<span className="interval-chip">Intervall: {item.asset.service_interval_months||12} Monate</span>}</div><div className="service-actions">{item.kind==="SERVICE"&&editable(item.asset)?<><form action={completeServiceAction}><input type="hidden" name="assetId" value={item.asset.id}/><button className="button small" type="submit">✓ Wartung erledigt</button></form><form action={rescheduleServiceAction} className="reschedule-form"><input type="hidden" name="assetId" value={item.asset.id}/><input name="nextServiceDate" type="date" defaultValue={item.date} required/><button className="button ghost small" type="submit">Verschieben</button></form></>:<Link className="button ghost small" href={`/app/assets/${item.asset.id}`}>Pass öffnen</Link>}</div></article>)}</section>}</>;
}
