import Link from "next/link";
import { acceptServiceAccessAction } from "@/app/actions/service-access";
import { Logo } from "@/components/logo";
import { getCurrentUser, normalizeEmail } from "@/lib/auth";
import { getServiceInviteByToken } from "@/lib/service-access";
import { getLocale } from "@/lib/i18n";

export const dynamic="force-dynamic";

export default async function ServiceInvitePage({params,searchParams}:{params:Promise<{token:string}>;searchParams:Promise<{error?:string}>}){
  const {token}=await params;const {error}=await searchParams;const invite=await getServiceInviteByToken(token);const user=await getCurrentUser();const en=(await getLocale())==="en";
  if(!invite)return <main className="public-page"><section className="public-pass container"><Logo/><article className="panel" style={{marginTop:32}}><span className="eyebrow">{en?"Service access":"Servicefreigabe"}</span><h1>{en?"Invitation unavailable":"Einladung nicht verfügbar"}</h1><p className="muted">{en?"The invitation is invalid, expired, or has already been used.":"Die Einladung ist ungültig, abgelaufen oder wurde bereits verwendet."}</p><Link className="button" href="/app">{en?"Go to NavoPass":"Zu NavoPass"}</Link></article></section></main>;
  const matching=Boolean(user&&normalizeEmail(user.email)===normalizeEmail(invite.email));
  const next=`/service-invite/${encodeURIComponent(token)}`;
  return <main className="public-page"><section className="public-pass container"><Logo/><article className="panel" style={{marginTop:32,maxWidth:720}}><span className="eyebrow">{en?"Service access":"Servicezugriff"}</span><h1>{en?"Edit one asset pass":"Einzelnen Objektpass bearbeiten"}</h1><p className="muted">{en?"This access permits service and maintenance entries only for the invited NavoPass. It does not make you a member of the entire household or team.":"Diese Freigabe erlaubt Service- und Wartungseinträge ausschließlich für den eingeladenen NavoPass. Sie macht dich nicht zum Mitglied des gesamten Haushalts oder Teams."}</p>{error&&<p className="form-error">{error}</p>}<div className="detail-list" style={{margin:"22px 0"}}><div><dt>{en?"Invited email":"Eingeladene E-Mail"}</dt><dd>{invite.email}</dd></div><div><dt>{en?"Access until":"Zugriff bis"}</dt><dd>{new Intl.DateTimeFormat(en?"en-US":"de-DE",{dateStyle:"medium",timeStyle:"short"}).format(new Date(invite.access_until))}</dd></div></div>{matching?<form action={acceptServiceAccessAction}><input type="hidden" name="token" value={token}/><button className="button" type="submit">{en?"Accept service access":"Servicezugriff annehmen"} →</button></form>:user?<><p className="form-error">{en?`You are signed in as ${user.email}. This invitation belongs to ${invite.email}.`:`Du bist aktuell als ${user.email} angemeldet. Diese Einladung gehört zu ${invite.email}.`}</p><Link className="button ghost" href="/app">{en?"Account":"Zum Konto"}</Link></>:<div style={{display:"flex",gap:12,flexWrap:"wrap"}}><Link className="button" href={`/login?next=${encodeURIComponent(next)}`}>{en?"Sign in":"Anmelden"} →</Link><Link className="button ghost" href={`/register?next=${encodeURIComponent(next)}`}>{en?"Create account":"Konto erstellen"}</Link></div>}<p className="muted" style={{marginTop:20,fontSize:13}}>{en?"The owner may revoke this access at any time. Write access ends automatically when it expires.":"Der Eigentümer kann diese Freigabe jederzeit widerrufen. Nach Ablauf endet der Schreibzugriff automatisch."}</p></article></section></main>;
}
