export const BILLING_SCHEMA_STATEMENTS = [
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS stripe_customer_id text`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS stripe_subscription_id text`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS stripe_price_id text`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS subscription_status text`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS subscription_current_period_end timestamptz`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS subscription_cancel_at_period_end boolean NOT NULL DEFAULT false`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS stripe_event_created bigint NOT NULL DEFAULT 0`,
  `CREATE UNIQUE INDEX IF NOT EXISTS users_stripe_customer_unique_idx ON users(stripe_customer_id) WHERE stripe_customer_id IS NOT NULL`,
  `CREATE UNIQUE INDEX IF NOT EXISTS users_stripe_subscription_unique_idx ON users(stripe_subscription_id) WHERE stripe_subscription_id IS NOT NULL`,
  `CREATE TABLE IF NOT EXISTS stripe_events (
    id text PRIMARY KEY,
    type text NOT NULL,
    created bigint NOT NULL,
    processed_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE INDEX IF NOT EXISTS stripe_events_processed_idx ON stripe_events(processed_at DESC)`,
  `CREATE TABLE IF NOT EXISTS billing_consents (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    plan text NOT NULL CHECK (plan IN ('PLUS','FAMILY','BUSINESS')),
    billing_interval text NOT NULL CHECK (billing_interval IN ('monthly','yearly')),
    terms_version text NOT NULL,
    terms_accepted_at timestamptz NOT NULL,
    withdrawal_acknowledged_at timestamptz NOT NULL,
    early_performance_requested_at timestamptz NOT NULL,
    stripe_checkout_session_id text,
    created_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS billing_consents_checkout_unique_idx ON billing_consents(stripe_checkout_session_id) WHERE stripe_checkout_session_id IS NOT NULL`,
  `CREATE INDEX IF NOT EXISTS billing_consents_user_idx ON billing_consents(user_id, created_at DESC)`,
  `CREATE TABLE IF NOT EXISTS cancellation_requests (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid REFERENCES users(id) ON DELETE SET NULL,
    email text NOT NULL,
    contract_label text NOT NULL,
    cancellation_kind text NOT NULL CHECK (cancellation_kind IN ('ORDINARY','EXTRAORDINARY')),
    reason text,
    requested_end_mode text NOT NULL CHECK (requested_end_mode IN ('NEXT_POSSIBLE','IMMEDIATE','DATE')),
    requested_end_date date,
    stripe_subscription_id text,
    processing_status text NOT NULL DEFAULT 'RECEIVED',
    processing_note text,
    receipt_token_hash text NOT NULL UNIQUE,
    requested_at timestamptz NOT NULL DEFAULT now(),
    confirmation_sent_at timestamptz,
    support_notified_at timestamptz
  )`,
  `CREATE INDEX IF NOT EXISTS cancellation_requests_email_idx ON cancellation_requests(lower(email), requested_at DESC)`,
  `CREATE INDEX IF NOT EXISTS cancellation_requests_status_idx ON cancellation_requests(processing_status, requested_at)`,
  `CREATE TABLE IF NOT EXISTS withdrawal_requests (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid REFERENCES users(id) ON DELETE SET NULL,
    consumer_name text NOT NULL,
    email text NOT NULL,
    contract_label text NOT NULL,
    stripe_subscription_id text,
    processing_status text NOT NULL DEFAULT 'RECEIVED',
    processing_note text,
    receipt_token_hash text NOT NULL UNIQUE,
    requested_at timestamptz NOT NULL DEFAULT now(),
    confirmation_sent_at timestamptz,
    support_notified_at timestamptz
  )`,
  `CREATE INDEX IF NOT EXISTS withdrawal_requests_email_idx ON withdrawal_requests(lower(email), requested_at DESC)`,
  `CREATE INDEX IF NOT EXISTS withdrawal_requests_status_idx ON withdrawal_requests(processing_status, requested_at)`,
] as const;
