export const SERVICE_WORKFLOW_SCHEMA_STATEMENTS = [
  `CREATE TABLE IF NOT EXISTS service_jobs (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    assigned_user_id uuid REFERENCES users(id) ON DELETE SET NULL,
    customer_id uuid,
    asset_id uuid NOT NULL REFERENCES assets(id) ON DELETE CASCADE,
    title text NOT NULL,
    scheduled_for timestamptz,
    estimated_duration_minutes integer NOT NULL DEFAULT 60 CHECK (estimated_duration_minutes BETWEEN 15 AND 720),
    notes text,
    priority text NOT NULL DEFAULT 'NORMAL' CHECK (priority IN ('LOW','NORMAL','HIGH')),
    status text NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','IN_PROGRESS','DONE','CANCELLED')),
    completed_event_id uuid REFERENCES asset_events(id) ON DELETE SET NULL,
    completed_at timestamptz,
    started_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
  )`,
  `ALTER TABLE service_jobs ADD COLUMN IF NOT EXISTS priority text NOT NULL DEFAULT 'NORMAL'`,
  `ALTER TABLE service_jobs ADD COLUMN IF NOT EXISTS started_at timestamptz`,
  `ALTER TABLE service_jobs ADD COLUMN IF NOT EXISTS assigned_user_id uuid REFERENCES users(id) ON DELETE SET NULL`,
  `ALTER TABLE service_jobs ADD COLUMN IF NOT EXISTS estimated_duration_minutes integer NOT NULL DEFAULT 60`,
  `ALTER TABLE service_jobs DROP CONSTRAINT IF EXISTS service_jobs_duration_check`,
  `ALTER TABLE service_jobs ADD CONSTRAINT service_jobs_duration_check CHECK (estimated_duration_minutes BETWEEN 15 AND 720)`,
  `ALTER TABLE service_jobs DROP CONSTRAINT IF EXISTS service_jobs_status_check`,
  `ALTER TABLE service_jobs ADD CONSTRAINT service_jobs_status_check CHECK (status IN ('OPEN','IN_PROGRESS','DONE','CANCELLED'))`,
  `ALTER TABLE service_jobs DROP CONSTRAINT IF EXISTS service_jobs_priority_check`,
  `ALTER TABLE service_jobs ADD CONSTRAINT service_jobs_priority_check CHECK (priority IN ('LOW','NORMAL','HIGH'))`,
  `CREATE INDEX IF NOT EXISTS service_jobs_user_status_idx ON service_jobs(user_id,status,scheduled_for)`,
  `CREATE INDEX IF NOT EXISTS service_jobs_assigned_status_idx ON service_jobs(assigned_user_id,status,scheduled_for)`,
  `CREATE INDEX IF NOT EXISTS service_jobs_asset_idx ON service_jobs(asset_id,created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS service_jobs_customer_idx ON service_jobs(customer_id,created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS service_jobs_schedule_idx ON service_jobs(user_id,scheduled_for) WHERE status IN ('OPEN','IN_PROGRESS')`,
  `CREATE TABLE IF NOT EXISTS service_report_shares (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    asset_id uuid NOT NULL REFERENCES assets(id) ON DELETE CASCADE,
    event_id uuid NOT NULL REFERENCES asset_events(id) ON DELETE CASCADE,
    created_by uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    recipient_email text NOT NULL,
    token_hash text NOT NULL UNIQUE,
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    opened_at timestamptz,
    revoked_at timestamptz
  )`,
  `ALTER TABLE service_report_shares ADD COLUMN IF NOT EXISTS revoked_at timestamptz`,
  `CREATE INDEX IF NOT EXISTS service_report_shares_event_idx ON service_report_shares(event_id,created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS service_report_shares_expiry_idx ON service_report_shares(expires_at)`,
] as const;
