export const SERVICE_REPORT_SCHEMA_STATEMENTS = [
  `ALTER TABLE asset_events ADD COLUMN IF NOT EXISTS labor_minutes integer`,
  `ALTER TABLE asset_events ADD COLUMN IF NOT EXISTS parts_used text`,
  `ALTER TABLE asset_events ADD COLUMN IF NOT EXISTS measurements text`,
  `ALTER TABLE asset_events ADD COLUMN IF NOT EXISTS findings text`,
  `ALTER TABLE asset_events ADD COLUMN IF NOT EXISTS recommendation text`,
  `ALTER TABLE asset_events ADD COLUMN IF NOT EXISTS customer_name text`,
  `ALTER TABLE asset_events ADD COLUMN IF NOT EXISTS customer_signature text`,
  `ALTER TABLE asset_events ADD COLUMN IF NOT EXISTS customer_signed_at timestamptz`,
  `ALTER TABLE asset_events ADD COLUMN IF NOT EXISTS report_asset_name text`,
  `ALTER TABLE asset_events ADD COLUMN IF NOT EXISTS report_asset_category text`,
  `ALTER TABLE asset_events ADD COLUMN IF NOT EXISTS report_asset_manufacturer text`,
  `ALTER TABLE asset_events ADD COLUMN IF NOT EXISTS report_asset_model text`,
  `ALTER TABLE asset_events ADD COLUMN IF NOT EXISTS report_asset_serial_number text`,
  `ALTER TABLE asset_events ADD COLUMN IF NOT EXISTS report_asset_location text`,
  `ALTER TABLE asset_events ADD COLUMN IF NOT EXISTS report_asset_public_id text`,
  `ALTER TABLE asset_events ADD COLUMN IF NOT EXISTS report_customer_name text`,
  `ALTER TABLE asset_events ADD COLUMN IF NOT EXISTS report_customer_contact_name text`,
  `ALTER TABLE asset_events ADD COLUMN IF NOT EXISTS report_customer_email text`,
  `ALTER TABLE asset_events ADD COLUMN IF NOT EXISTS report_customer_street text`,
  `ALTER TABLE asset_events ADD COLUMN IF NOT EXISTS report_customer_postal_code text`,
  `ALTER TABLE asset_events ADD COLUMN IF NOT EXISTS report_customer_city text`,
  `ALTER TABLE asset_events ADD COLUMN IF NOT EXISTS report_customer_country text`,
] as const;
