import Link from "next/link";
import { verifyEmailAction } from "@/app/actions/verification";
import { Logo } from "@/components/logo";
import styles from "@/app/auth.module.css";
import { getLocale } from "@/lib/i18n";

export default async function VerifyEmailPage({ searchParams }: { searchParams: Promise<{ token?: string; success?: string; error?: string }> }) {
  const { token = "", success, error } = await searchParams;
  const en = (await getLocale()) === "en";
  return <main className={styles.page}><header className={styles.header}><div className={styles.brand}><Logo /></div><Link className={styles.back} href="/app">← {en ? "NavoPass" : "Zu NavoPass"}</Link></header><section className={styles.shell}><aside className={styles.side}><div className={styles.sideInner}><span className={styles.eyebrow}>{en ? "Account security" : "Kontosicherheit"}</span><h2>{en ? "Confirm your email address." : "Bestätige deine E-Mail-Adresse."}</h2><p>{en ? "This ensures only authorized users can use invitations and security messages sent to this address." : "So können nur berechtigte Nutzer Einladungen und sicherheitsrelevante Nachrichten für diese Adresse verwenden."}</p></div></aside><div className={styles.formPane}><div className={styles.formBox}><span>{en ? "Confirm email" : "E-Mail bestätigen"}</span><h1>{success ? (en ? "Confirmed" : "Bestätigt") : (en ? "Verify address" : "Adresse verifizieren")}</h1>{success ? <><p className={styles.success}>{en ? "Your email address has been confirmed." : "Deine E-Mail-Adresse wurde erfolgreich bestätigt."}</p><Link className={styles.submitLink} href="/app">{en ? "Go to dashboard" : "Zum Dashboard"} →</Link></> : <>{error && <p className={styles.error}>{error}</p>}{token.length > 20 ? <form action={verifyEmailAction} className={styles.form}><input type="hidden" name="token" value={token} /><button className={styles.submit} type="submit">{en ? "Confirm email address" : "E-Mail-Adresse bestätigen"} →</button></form> : <><p className={styles.error}>{en ? "The confirmation link is missing or invalid." : "Der Bestätigungslink fehlt oder ist ungültig."}</p><Link className={styles.submitLink} href="/app">{en ? "Go to dashboard" : "Zum Dashboard"} →</Link></>}</>}<p className={styles.foot}><Link href="/kontakt">{en ? "Problems confirming?" : "Probleme mit der Bestätigung?"}</Link></p></div></div></section></main>;
}
